"""
Constantes: banco de figuras políticas, palavras-chave e configurações.
"""

import os

from dotenv import load_dotenv

load_dotenv()

TWITTER_BEARER_TOKEN = os.getenv('TWITTER_BEARER_TOKEN', '')
TIMEOUT = 12

# =========================
# BANCO DE FIGURAS POLÍTICAS CONHECIDAS
# score: -2 = esquerda forte, -1 = centro-esquerda,
#         0 = centro, 1 = centro-direita, 2 = direita forte
# =========================

FIGURAS_POLITICAS = {
    # ════════════════════════════════════════
    # PARTIDOS POLÍTICOS
    # ════════════════════════════════════════

    # ── PARTIDOS ESQUERDA (-2) ──
    'pt_brasil': ('PT', -2),
    'ptbrasil': ('PT', -2),
    'pcdoboficial': ('PCdoB', -2),
    'psol50': ('PSOL', -2),
    'psoloficial': ('PSOL', -2),

    # ── PARTIDOS CENTRO-ESQUERDA (-1) ──
    'pdt_oficial': ('PDT', -1),
    'pdtoficial': ('PDT', -1),
    'psbnacional': ('PSB', -1),
    'psb_nacional': ('PSB', -1),
    'redesustentabilidade': ('Rede Sustentabilidade', -1),
    'rede_sustentabilidade': ('Rede Sustentabilidade', -1),

    # ── PARTIDOS CENTRO (0) ──
    'mdbnacional': ('MDB', 0),
    'mdb_oficial': ('MDB', 0),
    'psd_oficial': ('PSD', 0),
    'psdoficial': ('PSD', 0),
    'cidadaniaoficial': ('Cidadania', 0),
    'movimentoavante': ('Avante', 0),
    'solidariedade_br': ('Solidariedade', 0),

    # ── PARTIDOS CENTRO-DIREITA (1) ──
    'psdb': ('PSDB', 1),
    'psdb_oficial': ('PSDB', 1),
    'uniaobrasil': ('União Brasil', 1),
    'uniao_brasil': ('União Brasil', 1),
    'podemos_br': ('Podemos', 1),
    'podemosoficial': ('Podemos', 1),
    'republicanos10': ('Republicanos', 1),
    'republicanosbr': ('Republicanos', 1),
    'pp_progressistas': ('Progressistas', 1),
    'partidonovo30': ('Partido NOVO', 1),

    # ── PARTIDOS DIREITA (2) ──
    'pl_brasil': ('PL', 2),
    'ploficial': ('PL', 2),

    # ════════════════════════════════════════
    # GOVERNO FEDERAL LULA — MINISTÉRIOS E ÓRGÃOS (-2)
    # ════════════════════════════════════════
    'minsaude': ('Ministério da Saúde', -2),
    'ministeriodasaude': ('Ministério da Saúde', -2),
    'minsaude_': ('Ministério da Saúde', -2),
    'govbr': ('Governo Federal', -2),
    'secomgovbr': ('Secom Gov BR', -2),
    'planalto': ('Palácio do Planalto', -2),
    'mineducacao': ('MEC', -2),
    'mec_brasil': ('MEC', -2),
    'mds_brasil': ('Min. Desenvolvimento Social', -2),
    'mds_gov': ('Min. Desenvolvimento Social', -2),
    'agenciabrasil': ('Agência Brasil', -2),
    'portalsus': ('Portal SUS', -2),
    'sus_oficial': ('SUS Oficial', -2),
    'conass_br': ('CONASS', -2),
    'fiocruz': ('Fiocruz', -2),
    'fiocruzoficial': ('Fiocruz', -2),
    'nilsiatrindade': ('Nilsia Trindade', -2),
    'lulasaude': ('Lula Saúde', -2),
    'cremesp': ('CREMESP', -2),
    'cfm_oficial': ('CFM', -2),
    'alexandresilveira': ('Alexandre Silveira', -2),
    'jorgemeseias': ('Jorge Messias', -2),
    'min_meio_ambiente': ('Min. Meio Ambiente', -2),
    'mcidades_oficial': ('Min. Cidades', -2),
    'mturismobrasil': ('Min. Turismo', -2),

    # ════════════════════════════════════════
    # GOVERNADORES
    # ════════════════════════════════════════

    # ── GOVERNADORES ESQUERDA (-2) ──
    'elmanofreitas': ('Elmano de Freitas (Gov. CE/PT)', -2),
    'jeronimobt': ('Jerônimo Rodrigues (Gov. BA/PT)', -2),
    'jeronimorodrigues': ('Jerônimo Rodrigues (Gov. BA/PT)', -2),
    'rafaelfonteles': ('Rafael Fonteles (Gov. PI/PT)', -2),
    'fatimabezerra': ('Fátima Bezerra (Gov. RN/PT)', -2),
    'camilosantana': ('Camilo Santana (Min. Educação/PT)', -2),

    # ── GOVERNADORES CENTRO-ESQUERDA (-1) ──
    'helderbarbalho': ('Helder Barbalho (Gov. PA/MDB)', -1),
    'helder_barbalho': ('Helder Barbalho (Gov. PA/MDB)', -1),
    'casagrande_es': ('Renato Casagrande (Gov. ES/PSB)', -1),
    'renatocasagrande': ('Renato Casagrande (Gov. ES/PSB)', -1),
    'joaocampos_': ('João Campos (Pref. Recife/PSB)', -1),
    'clecio_lm': ('Clécio Luís (Gov. AP/PDT)', -1),

    # ── GOVERNADORES CENTRO (0) ──
    'eduardoleite': ('Eduardo Leite (Gov. RS/PSDB)', 0),
    'ibaneisrocha': ('Ibaneis Rocha (Gov. DF/MDB)', 0),
    'raquellyra': ('Raquel Lyra (Gov. PE/PSDB)', 0),
    'paulodantas_al': ('Paulo Dantas (Gov. AL/MDB)', 0),

    # ── GOVERNADORES CENTRO-DIREITA (1) ──
    'tarcisiogdf': ('Tarcísio de Freitas (Gov. SP/Rep.)', 1),
    'romeuzema': ('Romeu Zema (Gov. MG/NOVO)', 1),
    'ronaldocaiado': ('Ronaldo Caiado (Gov. GO/União)', 1),
    'ratinhojunior': ('Ratinho Junior (Gov. PR/PSD)', 1),
    'mauro_mendes': ('Mauro Mendes (Gov. MT/União)', 1),
    'wanderlei_barbosa': ('Wanderlei Barbosa (Gov. TO/Rep.)', 1),
    'eduardoriedel': ('Eduardo Riedel (Gov. MS/PSDB)', 1),

    # ── GOVERNADORES DIREITA (2) ──
    'jorginhomello': ('Jorginho Mello (Gov. SC/PL)', 2),
    'claudiocastrorj': ('Cláudio Castro (Gov. RJ/PL)', 2),

    # ════════════════════════════════════════
    # SENADORES
    # ════════════════════════════════════════

    # ── SENADORES ESQUERDA (-2) ──
    'paulopaim': ('Paulo Paim (Sen. PT/RS)', -2),
    'fabiano_contarato': ('Fabiano Contarato (Sen. PT/ES)', -2),
    'humbertocosta': ('Humberto Costa (Sen. PT/PE)', -2),
    'jacqueswagner': ('Jaques Wagner (Sen. PT/BA)', -2),
    'rogeriocarvalhopt': ('Rogério Carvalho (Sen. PT/SE)', -2),
    'randolfe': ('Randolfe Rodrigues (Sen. PT/AP)', -2),
    'paulorocha_pt': ('Paulo Rocha (Sen. PT/PA)', -2),

    # ── SENADORES CENTRO-ESQUERDA (-1) ──
    'renancalheiros': ('Renan Calheiros (Sen. MDB/AL)', -1),
    'omaraziz': ('Omar Aziz (Sen. PSD/AM)', -1),
    'elizianegama': ('Eliziane Gama (Sen. PSD/MA)', -1),
    'weverton': ('Weverton Rocha (Sen. PDT/MA)', -1),

    # ── SENADORES CENTRO (0) ──
    'rodrigopacheco': ('Rodrigo Pacheco (Pres. Senado/PSD)', 0),

    # ── SENADORES CENTRO-DIREITA (1) ──
    'sergiomoro': ('Sérgio Moro (Sen. União/PR)', 1),
    'cironogueira': ('Ciro Nogueira (Sen. PP/PI)', 1),
    'efraim_filho': ('Efraim Filho (Sen. União/PB)', 1),
    'marcos_do_val': ('Marcos do Val (Sen. Podemos/ES)', 1),
    'marcopontes': ('Marcos Pontes (Sen. PL/SP)', 1),
    'astronautamarcos': ('Marcos Pontes (Sen. PL/SP)', 1),

    # ── SENADORES DIREITA (2) ──
    'flaviobolsonaro': ('Flávio Bolsonaro (Sen. PL/RJ)', 2),
    'damaresalves': ('Damares Alves (Sen. PL/DF)', 2),
    'general_girao': ('General Girão (Sen. PL/RN)', 2),
    'marcosrogerio': ('Marcos Rogério (Sen. PL/RO)', 2),

    # ════════════════════════════════════════
    # DEPUTADOS FEDERAIS
    # ════════════════════════════════════════

    # ── DEPUTADOS ESQUERDA (-2) ──
    'glauberbraga': ('Glauber Braga (Dep. PSOL/RJ)', -2),
    'taliria': ('Taliria Petrone (Dep. PSOL/RJ)', -2),
    'fmelchionna': ('Fernanda Melchionna (Dep. PSOL/RS)', -2),
    'fernandamelchionna': ('Fernanda Melchionna (Dep. PSOL/RS)', -2),
    'leopericles': ('Léo Péricles (Dep. PSOL/AM)', -2),
    'erikakokay': ('Erika Kokay (Dep. PT/DF)', -2),
    'pimenta13': ('Paulo Pimenta (Dep. PT/RS)', -2),
    'beneditapt': ('Benedita da Silva (Dep. PT/RJ)', -2),
    'reginaldolopes': ('Reginaldo Lopes (Dep. PT/MG)', -2),
    'aliceportugal': ('Alice Portugal (Dep. PCdoB/BA)', -2),
    'chicoalencar': ('Chico Alencar (Dep. PSOL/RJ)', -2),
    'ruifalcao': ('Rui Falcão (Dep. PT/SP)', -2),
    'zecadirceu': ('Zeca Dirceu (Dep. PT/PR)', -2),
    'samiabomfim': ('Sâmia Bomfim (Dep. PSOL/SP)', -2),
    'andrejanonesadv': ('André Janones (Dep. Avante/MG)', -2),
    'guilhermeboulos': ('Guilherme Boulos (Dep. PSOL/SP)', -2),
    'guilherme.boulos': ('Guilherme Boulos (Dep. PSOL/SP)', -2),
    'jandirafeghali': ('Jandira Feghali (Dep. PCdoB/RJ)', -2),
    'marcelofreixo': ('Marcelo Freixo (Dep. PT/RJ)', -2),
    # PT
    'josenildopt': ('Josenildo (Dep. PT/AP)', -2),
    'carlosamedina': ('Carlos Veras (Dep. PT/PE)', -2),
    'carlosveras': ('Carlos Veras (Dep. PT/PE)', -2),
    'petecosta': ('Petecosteff (Dep. PT/SP)', -2),
    'valmirnascimento': ('Valmir Assunção (Dep. PT/BA)', -2),
    'valmirassuncaopt': ('Valmir Assunção (Dep. PT/BA)', -2),
    'joaodanielpt': ('João Daniel (Dep. PT/SE)', -2),
    'afonsoaranhapt': ('Afonso Motta (Dep. PT/RS)', -2),
    'afonsomottapt': ('Afonso Motta (Dep. PT/RS)', -2),
    'airtonfaleiro': ('Airton Faleiro (Dep. PT/PA)', -2),
    'alencarbraga': ('Alencar Braga (Dep. PT/AM)', -2),
    'alexandrepadilha': ('Alexandre Padilha (Min. Rel. Institucionais/PT)', -2),
    'aninhafigueiredo': ('Ana Figueiredo (Dep. PT/PE)', -2),  # Ana Paula Lemos
    'claudiobragage': ('Cláudio Cajado (Dep. PP/BA)', 1),  # movido abaixo
    'costaluz': ('Bohn Gass (Dep. PT/RS)', -2),
    'bonhgass': ('Bohn Gass (Dep. PT/RS)', -2),
    'danielaribeiropt': ('Daniela Carneiro (Dep. União/RJ)', 1),  # movido abaixo
    'dionisiobelchior': ('Dionísio Belchior (Dep. PT/CE)', -2),
    'eleonoraol': ('Erika Hilton (Dep. PSOL/SP)', -2),
    'erikahilton': ('Erika Hilton (Dep. PSOL/SP)', -2),
    'fernandomineiro': ('Fernando Mineiro (Dep. PT/SE)', -2),
    'gastaovieira': ('Gastão Vieira (Dep. PROS/MA)', -1),
    'heliosoficialbr': ('Hélio Lopes (Dep. PL/RJ)', 2),  # movido abaixo
    'irinyeu': ('Irineu Jansen (Dep. PT/MA)', -2),
    'joaophilipe': ('João Philippe (Dep. PSOL/RJ)', -2),
    'jorgewilson': ('Jorge Wilson (Dep. Rep./RR)', 1),  # movido abaixo
    'kominkasaopaulo': ('Komi (Dep. PT/SP)', -2),
    'lauraborakosc': ('Laura Carneiro (Dep. PSD/RJ)', 0),  # movido abaixo
    'lincolnportelamt': ('Lincoln Portela (Dep. PL/MG)', 2),  # movido abaixo
    'luizaerundina': ('Luíza Erundina (Dep. PSOL/SP)', -2),
    'luizaerundina_oficial': ('Luíza Erundina (Dep. PSOL/SP)', -2),
    'mariajosemaneira': ('Maria José (Dep. PT/PA)', -2),
    'patricklopes': ('Patrick Lopes (Dep. PT/MG)', -2),
    'pauloteixeiraptsp': ('Paulo Teixeira (Dep. PT/SP)', -2),
    'pauloteixeira_ptsp': ('Paulo Teixeira (Dep. PT/SP)', -2),
    'pedropartidario': ('Pedro Uczai (Dep. PT/SC)', -2),
    'pedroupczai': ('Pedro Uczai (Dep. PT/SC)', -2),
    'professorlissauer': ('Professora Luciene (Dep. PSOL/SP)', -2),
    'professoraluciene': ('Professora Luciene (Dep. PSOL/SP)', -2),
    'ricardosouza_ptba': ('Ricardo Maia (Dep. PT/BA)', -2),
    'rogeriocorreaneto': ('Rogério Corrêa (Dep. PT/MG)', -2),
    'rogeriocorrea': ('Rogério Corrêa (Dep. PT/MG)', -2),
    'rosangelalomba': ('Rosângela Moro (Dep. União/SP)', 1),  # movido abaixo
    'vicentinhosp': ('Vicentinho (Dep. PT/SP)', -2),
    'vicentinhopt': ('Vicentinho (Dep. PT/SP)', -2),
    'zeze_pt': ('Zezé Perrella (Sen. PSD/MG)', 0),  # movido

    # PCdoB
    'adailbenedet': ('Adail Filho (Dep. Rep./AM)', 1),  # movido abaixo
    'aruanaborges': ('Aruana Borges (Dep. PCdoB/GO)', -2),
    'danielmendes_': ('Daniel Almeida (Dep. PCdoB/BA)', -2),
    'danielalmeidapt': ('Daniel Almeida (Dep. PCdoB/BA)', -2),
    'doutorluizinho': ('Dr. Luizinho (Dep. PL/RJ)', 2),  # movido abaixo
    'fclementepcdob': ('Francisco Clemente (Dep. PCdoB/MA)', -2),
    'leonardopericles': ('Léo Péricles (Dep. UP/AM)', -2),
    'marcelorom': ('Marcelo Rom (Dep. PCdoB/DF)', -2),
    'pauloguimares_': ('Paulo Guimarães (Dep. PCdoB/DF)', -2),
    'perpituaoficial': ('Perpétua Almeida (Dep. PCdoB/AC)', -2),
    'perpétuaalmeida': ('Perpétua Almeida (Dep. PCdoB/AC)', -2),

    # PSOL
    'boulos': ('Guilherme Boulos (Dep. PSOL/SP)', -2),
    'dougrasfalcao': ('Dougras Falcão (Dep. PSOL/BA)', -2),
    'priammon': ('Pri Ammon (Dep. PSOL/RJ)', -2),
    'priammonoficial': ('Pri Ammon (Dep. PSOL/RJ)', -2),
    'raylane_psol': ('Raylane (Dep. PSOL/PA)', -2),
    'taliriaoficial': ('Taliria Petrone (Dep. PSOL/RJ)', -2),
    'thiagoavila_psol': ('Thiago Ávila (Dep. PSOL/RR)', -2),

    # ── DEPUTADOS CENTRO-ESQUERDA (-1) ──
    'alessandromolon': ('Alessandro Molon (Dep. PSB/RJ)', -1),
    'tabataamaralsp': ('Tabata Amaral (Dep. PSB/SP)', -1),
    'tabata.amaral': ('Tabata Amaral (Dep. PSB/SP)', -1),
    'marcelo_calero': ('Marcelo Calero (Dep. Cidadania/RJ)', -1),
    # PSB
    'adolfovaindermansb': ('Adolfo Vainberger (Dep. PSB/SP)', -1),
    'bacelarpsb': ('Bacelar (Dep. PSB/BA)', -1),
    'bacelarba': ('Bacelar (Dep. PSB/BA)', -1),
    'bliro_maggi': ('Blairo Maggi (ex-Sen.)', 1),  # movido abaixo
    'davidmelo_rn': ('David Melo (Dep. PSB/RN)', -1),
    'evairdefaria': ('Evair de Melo (Dep. PP/ES)', 1),  # movido abaixo
    'fabioabramof': ('Fábio Abramof (Dep. PSB/SP)', -1),
    'jorgebraz': ('Jorge Braz (Dep. PSB/RJ)', -1),
    'leokoury': ('Leo Koury (Dep. PSB/PE)', -1),
    'mariaarruda_psb': ('Maria Arruda (Dep. PSB/RN)', -1),
    # PDT
    'andrefigpsb': ('André Figueiredo (Dep. PDT/CE)', -1),
    'andrefigueiredo_': ('André Figueiredo (Dep. PDT/CE)', -1),
    'wolneyqueiroz': ('Wolney Queiroz (Dep. PDT/PE)', -1),
    # Avante
    'elmarnascimento': ('Elmar Nascimento (Dep. União/BA)', 1),  # movido abaixo
    # Solidariedade
    'paulinhosolidario': ('Paulinho da Força (Dep. Solid./SP)', 0),
    'paulinhodaforca': ('Paulinho da Força (Dep. Solid./SP)', 0),
    # Rede
    'carlosgutierre': ('Carlos Gutierre (Dep. Rede/CE)', -1),

    # ── DEPUTADOS CENTRO (0) ──
    'baleiarodrigues': ('Baleia Rossi (Dep. MDB/SP)', 0),
    'baleia_rossi': ('Baleia Rossi (Dep. MDB/SP)', 0),
    'henriquemeirelles': ('Henrique Meirelles (Dep. União/GO)', 0),
    'lauracarneiro': ('Laura Carneiro (Dep. PSD/RJ)', 0),
    'mafraotavia': ('Otávio Mafra (Dep. PSB/SE)', -1),
    'paulinhodaforça': ('Paulinho da Força (Dep. Solid./SP)', 0),
    'sidrinha_psd': ('Sidney Leite (Dep. PSD/AM)', 0),
    # MDB
    'danielcoeljr': ('Daniel Coelho (Dep. PSD/PE)', 0),
    'emanuelpeironmdb': ('Emanuela Peron (Dep. MDB/MG)', 0),
    'luciosalles': ('Lúcio Salles (Dep. MDB/PR)', 0),
    'marciojerusalem': ('Márcio Biolchi (Dep. MDB/RS)', 0),
    'marcosbezerra': ('Marcos Bezerra (Dep. MDB/RR)', 0),
    'rafaelbecker_': ('Rafael Becker (Dep. MDB/RS)', 0),
    # PSD
    'cintiabarradc': ('Cintia Barra (Dep. PSD/RS)', 0),
    'fernandafierro': ('Fernanda Melchior (Dep. PSD/MT)', 0),
    'flavinopp': ('Flaviano Melo (Dep. MDB/AC)', 0),
    'gilliatpereira': ('Gilli Pereira (Dep. PSD/TO)', 0),
    'leomoura_': ('Léo Moura (Dep. PSD/RJ)', 0),
    'marxbeltrão': ('Marx Beltrão (Dep. PSD/AL)', 0),
    'primoralespsd': ('Primo Morales (Dep. PSD/MS)', 0),
    'rodrigomayapsd': ('Rodrigo Maia (ex-Dep.)', 0),
    'thiagosilva_psd': ('Thiago Silva (Dep. PSD/ES)', 0),
    # Podemos
    'albertomourao': ('Hamilton Mourão (Sen. Rep./RS)', 1),  # movido abaixo

    # ── DEPUTADOS CENTRO-DIREITA (1) ──
    'arthurlira': ('Arthur Lira (Dep. PP/AL)', 1),
    'kimkataguiri': ('Kim Kataguiri (Dep. MDB/SP)', 1),
    'marcelvanhattem': ('Marcel van Hattem (Dep. NOVO/RS)', 1),
    'osmarterra': ('Osmar Terra (Dep. MDB/RS)', 1),
    # PP
    'cenourasenna': ('Cenoura Senna (Dep. PP/RO)', 1),
    'claudiocajado': ('Cláudio Cajado (Dep. PP/BA)', 1),
    'duartejuniorpp': ('Duarte Jr. (Dep. Rep./MA)', 1),
    'generalleal': ('General Leal (Dep. PL/RJ)', 2),  # movido abaixo
    'igoreterno': ('Igor Eterno (Dep. PP/RO)', 1),
    'joaoromaopp': ('João Romão (Dep. PP/GO)', 1),
    'paolamassarpp': ('Paola Massari (Dep. PP/PR)', 1),
    'sandratorres_': ('Sandra Torres (Dep. PP/PR)', 1),
    # PSDB
    'aecio_neves': ('Aécio Neves (Dep. PSDB/MG)', 1),
    'aecioneves': ('Aécio Neves (Dep. PSDB/MG)', 1),
    'danielcamarapsdb': ('Daniel Câmara (Dep. PSDB/SP)', 1),
    # União Brasil
    'elmaroficial': ('Elmar Nascimento (Dep. União/BA)', 1),
    'elmar_nascimento': ('Elmar Nascimento (Dep. União/BA)', 1),
    'flavio_braide': ('Flávio Braide (Dep. União/MA)', 1),
    'juniordojuara': ('Júnior do Juara (Dep. União/MT)', 1),
    'marcelfreitas_': ('Marcel Freitas (Dep. União/AM)', 1),
    'papitomayorga': ('Papito Rodrigues (Dep. União/PA)', 1),
    'rosangelamoro': ('Rosângela Moro (Dep. União/SP)', 1),
    'rodolfolutzuniao': ('Rodolfo Lutz (Dep. União/SC)', 1),
    'silviobrasil': ('Sílvio Costa Filho (Dep. Rep./PE)', 1),
    # Republicanos
    'celsorussman': ('Celso Russomanno (Dep. Rep./SP)', 1),
    'celsorussomanno': ('Celso Russomanno (Dep. Rep./SP)', 1),
    'dougrasramos': ('Dougras Ramos (Dep. Rep./RJ)', 1),
    'generalrondoni': ('General Rondoni (Dep. Rep./RJ)', 1),
    'migueltorner': ('Miguel Torner (Dep. Rep./RS)', 1),
    'rodrigodepaula': ('Rodrigo de Paula (Dep. Rep./SP)', 1),
    # NOVO
    'alexmanente': ('Alex Manente (Dep. Cidadania/SP)', 0),
    'lucascnnbrasil': ('Lucas Japão (Dep. NOVO/SP)', 1),
    'luiz_ph': ('Luiz Philippe de Orléans (Dep. PL/RJ)', 2),
    'neilescolastico': ('Neil Escolástico (Dep. NOVO/PE)', 1),
    'paulomirza_novo': ('Paulo Mirza (Dep. NOVO/ES)', 1),
    'rickardamato': ('Rickard Amato (Dep. NOVO/SP)', 1),
    'tiagomitraud': ('Tiago Mitraud (Dep. NOVO/MG)', 1),
    # Podemos
    'albertomourao': ('Hamilton Mourão (Sen. Rep./RS)', 1),
    'christianpaescpo': ('Christian Paes (Dep. Podemos/RJ)', 1),
    'fernandahaasler': ('Fernanda Haasler (Dep. Podemos/RJ)', 1),
    'rodrigomartins__': ('Rodrigo Martins (Dep. União/PI)', 1),

    # ── DEPUTADOS DIREITA (2) ──
    'nikolasferreira': ('Nikolas Ferreira (Dep. PL/MG)', 2),
    'carlazambelli': ('Carla Zambelli (Dep. PL/SP)', 2),
    'eduardobolsonaro': ('Eduardo Bolsonaro (Dep. PL/SP)', 2),
    'edubolsonaro': ('Eduardo Bolsonaro (Dep. PL/SP)', 2),
    'carlosbolsonaro': ('Carlos Bolsonaro (Ver. PL/RJ)', 2),
    'biakicis': ('Bia Kicis (Dep. PL/DF)', 2),
    'marcofeliciano': ('Marco Feliciano (Dep. PL/SP)', 2),
    'sostenescavalcante': ('Sóstenes Cavalcante (Dep. PL/RJ)', 2),
    'coroneltadeu': ('Coronel Tadeu (Dep. PL/SP)', 2),
    'andrefernandes': ('André Fernandes (Dep. PL/CE)', 2),
    'christonietto': ('Chris Tonietto (Dep. PL/RJ)', 2),
    'danielsilveirarj': ('Daniel Silveira (Dep. PL/RJ)', 2),
    'jairrenan_': ('Jair Renan (Dep. PL/SC)', 2),
    # PL
    'adrianosalave': ('Adriano Salávea (Dep. PL/MT)', 2),
    'alexandremisael': ('Alexandre Misael (Dep. PL/PE)', 2),
    'alexsandretorres': ('Alexsandre Torres (Dep. PL/GO)', 2),
    'amomoral': ('Amo Moral (Dep. PL/RS)', 2),
    'andersonmoraes': ('Anderson Moraes (Dep. PL/RJ)', 2),
    'andersonmoraes_': ('Anderson Moraes (Dep. PL/RJ)', 2),
    'capitaodalmas': ('Capitão Dalmas (Dep. PL/RS)', 2),
    'capitaofabio': ('Capitão Fábio (Dep. PL/SP)', 2),
    'capitaogilberto': ('Capitão Gilberto (Dep. PL/SP)', 2),
    'carolinedemoraes': ('Caroline de Morais (Dep. PL/PA)', 2),
    'caucepederiva': ('Cauce Pederiva (Dep. PL/AP)', 2),
    'celsinoraschoficial': ('Celso Russomanno', 1),  # duplicado — veja Rep.
    'celenodario': ('Celeno Dário (Dep. PL/PA)', 2),
    'coronelmeira': ('Coronel Meira (Dep. PL/PE)', 2),
    'coronelnoronha': ('Coronel Noronha (Dep. PL/MG)', 2),
    'coronelzucco': ('Coronel Zucco (Dep. PL/RS)', 2),
    'dariobergher': ('Dario Bergher (Dep. PL/RJ)', 2),
    'delegadakatia': ('Delegada Kátia (Dep. PL/SC)', 2),
    'delegadopaulobilynskyj': ('Delegado Bilynsky (Dep. PL/PR)', 2),
    'delegadozucco': ('Coronel Zucco (Dep. PL/RS)', 2),
    'diogeniooliveira': ('Diogênio Oliveira (Dep. PL/AM)', 2),
    'doutorluizinhors': ('Dr. Luizinho (Dep. PL/RJ)', 2),
    'doutorluizinhopl': ('Dr. Luizinho (Dep. PL/RJ)', 2),
    'drluizinho': ('Dr. Luizinho (Dep. PL/RJ)', 2),
    'duvalpl': ('Duval Fernandes (Dep. PL/MG)', 2),
    'emersonpelegrin': ('Emerson Pelegrini (Dep. PL/PR)', 2),
    'evandroofficiall': ('Evandro Martins (Dep. PL/RO)', 2),
    'fabricioqueiroz': ('Fabrício Queiroz (ex-assessor)', 2),
    'fernandocorrealima': ('Fernando Corrêa (Dep. PL/MT)', 2),
    'filipebarrospl': ('Filipe Barros (Dep. PL/PR)', 2),
    'filipebarros': ('Filipe Barros (Dep. PL/PR)', 2),
    'flaviocastillo': ('Flávio Castillo (Dep. PL/DF)', 2),
    'fredbraga_': ('Fred Braga (Dep. PL/RO)', 2),
    'generalleal': ('General Leal (Dep. PL/RJ)', 2),
    'generalmouraooficial': ('Hamilton Mourão (Sen. Rep./RS)', 1),
    'gloriaheitera': ('Glória Heitera (Dep. PL/RS)', 2),
    'gustavogayerdep': ('Gustavo Gayer (Dep. PL/GO)', 2),
    'gustavogayer': ('Gustavo Gayer (Dep. PL/GO)', 2),
    'heliosoficialbr': ('Hélio Lopes (Dep. PL/RJ)', 2),
    'heliofernandes_': ('Hélio Fernandes (Dep. PL/RR)', 2),
    'henrymusspl': ('Henry Muss (Dep. PL/SC)', 2),
    'ismaelwpacheco': ('Ismael Pacheco (Dep. PL/GO)', 2),
    'jailsonmarcelino': ('Jailson Marcelino (Dep. PL/AP)', 2),
    'jalesromero': ('Jales Romo (Dep. PL/MT)', 2),
    'jenilsonleite': ('Jenilson Leite (Dep. PCdoB/AC)', -2),
    'joaobatistaapl': ('João Batista (Dep. PL/MG)', 2),
    'jorgeportela': ('Jorge Portela (Dep. PL/RJ)', 2),
    'juliorodrigues': ('Júlio Rodrigues (Dep. PL/RJ)', 2),
    'katiaabreu': ('Kátia Abreu (ex-Sen.)', 0),
    'leonardocurtis': ('Leonardo Curtis (Dep. PL/SP)', 2),
    'lincolnportela': ('Lincoln Portela (Dep. PL/MG)', 2),
    'luizaugustol': ('Luiz Augusto Lins (Dep. PL/SP)', 2),
    'luizphilippe': ('Luiz Philippe de Orléans (Dep. PL/RJ)', 2),
    'luizphilippedeorleansebraganca': ('Luiz Philippe de Orléans (Dep. PL/RJ)', 2),
    'marciolavareda': ('Márcio Lavareda (Dep. PL/PA)', 2),
    'marcoaurelioribeiro': ('Marco Aurélio Ribeiro (Dep. PL/TO)', 2),
    'mauriciodovolei': ('Maurício Dziedricki (Dep. PL/RS)', 2),
    'mauricioferreira': ('Maurício Ferreira (Dep. PL/PE)', 2),
    'micaelajeovara': ('Micaela Jeovara (Dep. PL/PA)', 2),
    'miguelhakin': ('Miguel Hakin (Dep. PL/AM)', 2),
    'milenaviana': ('Milena Viana (Dep. PL/RO)', 2),
    'mosquini': ('Mosquini (Dep. MDB/RO)', 0),
    'nelsontrevisol': ('Nelson Trevisol (Dep. PL/SC)', 2),
    'ninacarneiro': ('Nina Carneiro (Dep. PL/BA)', 2),
    'novallon': ('Nivalton (Dep. PL/RO)', 2),
    'paulosergio_pl': ('Paulo Sérgio (Dep. PL/PR)', 2),
    'rodrigobeckerpl': ('Rodrigo Becker (Dep. PL/MT)', 2),
    'rodrigovaiadao': ('Rodrigo Vaiadão (Dep. PL/ES)', 2),
    'ronaldonogueira': ('Ronaldo Nogueira (Dep. PL/RS)', 2),
    'romero_rodrigues': ('Romero Rodrigues (Dep. PL/PB)', 2),
    'saulomoura': ('Saulo Moura (Dep. PL/TO)', 2),
    'stefanofontes': ('Stefano Fontes (Dep. PL/SE)', 2),
    'thallesbarros': ('Thalles Barros (Dep. PL/RJ)', 2),
    'torquatobritopl': ('Torquato Brito (Dep. PL/PI)', 2),
    'wellisonbezerra': ('Wellison Bezerra (Dep. PL/CE)', 2),
    'williamwoo': ('William Woo (Dep. PL/SP)', 2),

    # ════════════════════════════════════════
    # LIDERANÇAS NACIONAIS — ESQUERDA (-2)
    # ════════════════════════════════════════
    'lulaoficial': ('Lula', -2),
    'labordes': ('Lula', -2),
    'dilmabr': ('Dilma Rousseff', -2),
    'gleisihoffmannoficial': ('Gleisi Hoffmann', -2),
    'gleisihoffmann': ('Gleisi Hoffmann', -2),
    'fernandohaddad': ('Fernando Haddad', -2),
    'gduvivier': ('Gregório Duvivier', -2),
    'gregorioduvivier': ('Gregório Duvivier', -2),
    'jeanwyllys_real': ('Jean Wyllys', -2),
    'brenoaltman': ('Breno Altman', -2),
    'jonesmanoel': ('Jones Manoel', -2),
    'sabrinafernandes': ('Sabrina Fernandes', -2),
    'tempodecerejas': ('Sabrina Fernandes', -2),
    'brasil247': ('Brasil 247', -2),
    'dcm_online': ('DCM Online', -2),
    'midia_ninja': ('Mídia NINJA', -2),
    'midianinja': ('Mídia NINJA', -2),
    'tv247': ('TV 247', -2),
    'conversaafiada': ('Conversa Afiada', -2),
    'revistaforum': ('Revista Fórum', -2),
    'operamundi': ('Opera Mundi', -2),

    # ── LIDERANÇAS CENTRO-ESQUERDA (-1) ──
    'cirogomes': ('Ciro Gomes', -1),
    'marinasilvabr': ('Marina Silva', -1),
    'marinasilva': ('Marina Silva', -1),
    'flaviodino': ('Flávio Dino', -1),
    'reinaldoazevedo': ('Reinaldo Azevedo', -1),
    'luisnassif': ('Luís Nassif', -1),
    'leonardosakamoto': ('Leonardo Sakamoto', -1),
    'jucakfouri': ('Juca Kfouri', -1),
    'cartacapital': ('Carta Capital', -1),
    'theintercept_br': ('The Intercept Brasil', -1),
    'theinterceptbr': ('The Intercept Brasil', -1),

    # ── LIDERANÇAS / IMPRENSA CENTRO-DIREITA (1) ──
    'hamiltonmourao': ('Hamilton Mourão (Sen. Rep./RS)', 1),

    # ════════════════════════════════════════
    # IMPRENSA E MÍDIA — CENTRO (0)
    # ════════════════════════════════════════
    'folha': ('Folha de S.Paulo', 0),
    'folhadespaulo': ('Folha de S.Paulo', 0),
    'estadao': ('Estadão', 0),
    'oglobo_rio': ('O Globo', 0),
    'oglobo': ('O Globo', 0),
    'g1': ('G1', 0),
    'portalg1': ('G1', 0),
    'uol': ('UOL', 0),
    'uolnoticias': ('UOL Notícias', 0),
    'bbcbrasil': ('BBC Brasil', 0),
    'cnn_brasil': ('CNN Brasil', 0),
    'cnnbrasil': ('CNN Brasil', 0),
    'bandnewsfm': ('BandNews', 0),
    'sbtonline': ('SBT', 0),
    'recordtv': ('Record', 0),
    'jornalnacional': ('Jornal Nacional', 0),
    'correio_braziliense': ('Correio Braziliense', 0),
    'valoreconomico': ('Valor Econômico', 0),
    'agenciasenadobr': ('Agência Senado', 0),
    'agenciacamara': ('Agência Câmara', 0),

    # ── IMPRENSA CENTRO-DIREITA (1) ──
    'oantagonista': ('O Antagonista', 1),
    'gazetadopovo': ('Gazeta do Povo', 1),
    'jovempannews': ('Jovem Pan News', 1),
    'jovempan': ('Jovem Pan', 1),
    'alexandregarcia': ('Alexandre Garcia', 1),
    'leandronarloch': ('Leandro Narloch', 1),

    # ── LIDERANÇAS / IMPRENSA DIREITA (2) ──
    'jairbolsonaro': ('Jair Bolsonaro', 2),
    'bolsonaro': ('Jair Bolsonaro', 2),
    'michellebolsonaro': ('Michelle Bolsonaro', 2),
    'rodrigoconstantino': ('Rodrigo Constantino', 2),
    'allandossantos': ('Allan dos Santos', 2),
    'bernardopkuster': ('Bernardo P. Küster', 2),
    'gustavogayer': ('Gustavo Gayer (Dep. PL/GO)', 2),
    'pablomarcal': ('Pablo Marçal', 2),
    'pablo_marcal': ('Pablo Marçal', 2),
    'revistaoeste': ('Revista Oeste', 2),
    'brasilparalelo': ('Brasil Paralelo', 2),
    'bparalelo': ('Brasil Paralelo', 2),
    'tercalivre': ('Terça Livre', 2),
    'sensoincomum': ('Senso Incomum', 2),
    'conexaopolitica': ('Conexão Política', 2),
}

# Nomes para busca textual em notícias/bio
NOMES_ESQUERDA = {
    'lula',
    'dilma',
    'haddad',
    'boulos',
    'gleisi',
    'janones',
    'jandira feghali',
    'marcelo freixo',
    'flavio dino',
    'marina silva',
    'ciro gomes',
    'samia bomfim',
    'jean wyllys',
    'jones manoel',
    'sabrina fernandes',
    'gregorio duvivier',
    'leonardo sakamoto',
    'luis nassif',
    'juca kfouri',
    'psol',
    'pcdob',
    'partido dos trabalhadores',
    'brasil 247',
    'dcm online',
    'carta capital',
    'the intercept',
    'midia ninja',
    'opera mundi',
    'revista forum',
    'ministerio da saude',
    'ministerio da educacao',
    'ministerio do desenvolvimento',
    'governo federal',
    'governo lula',
    'palacio do planalto',
    'fiocruz',
    'agencia brasil',
    'nilsia trindade',
    'elmano de freitas',
    'jeronimo rodrigues',
    'fatima bezerra',
    'camilo santana',
    'helder barbalho',
    'randolfe rodrigues',
    'humberto costa',
    'paulo paim',
    'erika hilton',
    'taliria petrone',
    'fernanda melchionna',
    'leo pericles',
    'luiza erundina',
    'perpétua almeida',
    'alice portugal',
    'benedita da silva',
    'paulo teixeira',
    'vicentinho',
}

NOMES_DIREITA = {
    'jair bolsonaro',
    'michelle bolsonaro',
    'flavio bolsonaro',
    'carlos bolsonaro',
    'eduardo bolsonaro',
    'sergio moro',
    'romeu zema',
    'tarcisio de freitas',
    'nikolas ferreira',
    'carla zambelli',
    'damares alves',
    'pablo marcal',
    'gustavo gayer',
    'bia kicis',
    'marco feliciano',
    'kim kataguiri',
    'marcel van hattem',
    'rodrigo constantino',
    'leandro narloch',
    'allan dos santos',
    'bernardo kuster',
    'olavo de carvalho',
    'daniel silveira',
    'marcos rogerio',
    'sostenes cavalcante',
    'revista oeste',
    'o antagonista',
    'gazeta do povo',
    'jovem pan',
    'brasil paralelo',
    'terca livre',
    'senso incomum',
    'conexao politica',
    'ronaldo caiado',
    'jorginho mello',
    'claudio castro',
    'wanderlei barbosa',
    'escola sem partido',
    'coronel tadeu',
    'coronel zucco',
    'filipe barros',
    'chris tonietto',
    'andre fernandes',
    'lincoln portela',
    'helio lopes',
    'luiz philippe',
    'anderson moraes',
    'capitao fabio',
}

PALAVRAS_ESQUERDA = {
    'igualdade',
    'feminismo',
    'feminista',
    'lgbtqia',
    'indigena',
    'quilombola',
    'socialismo',
    'socialista',
    'progressista',
    'antifascismo',
    'antifascista',
    'redistribuicao',
    'minorias',
    'oprimidos',
    'esquerda',
    'progressismo',
    'inclusao',
    'diversidade',
    'psol',
    'pcdob',
    'lula',
    'dilma',
    'boulos',
    'haddad',
    'janones',
    'freixo',
    'sakamoto',
    'vacinacao',
    'sus',
    'desigualdade',
    'trabalhismo',
    'trabalhista',
    'saude publica',
    'saude coletiva',
    'politica publica',
    'politicas publicas',
    'assistencia social',
    'educacao publica',
    'bolsa familia',
    'saude mental',
    'combate a fome',
    'fome zero',
    'cotas raciais',
    'acao afirmativa',
    'movimento social',
    'movimentos sociais',
    'reforma agraria',
    'direitos humanos',
    'direitos trabalhistas',
    'renda basica',
}

PALAVRAS_DIREITA = {
    'meritocracia',
    'bolsonaro',
    'bolsonarismo',
    'bolsonarista',
    'petismo',
    'petista',
    'agronegocio',
    'neoliberalismo',
    'privatismo',
    'anticomunismo',
    'anticomunista',
    'antiesquerda',
    'doutrinacao',
    'globalismo',
    'globalista',
    'nikolas',
    'zambelli',
    'marcal',
    'gayer',
    'privatizacao',
    'comunismo',
    'marxismo',
    'marxista',
    'conservadorismo',
    'olavismo',
    'olavista',
    'armamentismo',
    'petralha',
    'mortadela',
    'patriotismo',
    'kit gay',
    'ideologia de genero',
    'familia tradicional',
    'valores conservadores',
    'escola sem partido',
    'estado minimo',
    'livre mercado',
    'voto impresso',
    'fraude eleitoral',
    'intervencao militar',
    'globo mentira',
    'mamae falei',
    'brasil acima de tudo',
    'deus acima de todos',
    'porte de arma',
    'imposto e roubo',
    'contra o aborto',
    'comunismo na educacao',
    'aparelhamento do estado',
    'menos estado',
}