"""
Trecho gerado automaticamente por scraper_camara.py
Cole dentro de FIGURAS_POLITICAS em dados.py
"""

# ════════════════════════════════════════
# DEPUTADOS FEDERAIS — gerado por scraper_camara.py
# ════════════════════════════════════════
{
    # ── DEPUTADOS ESQUERDA (-2) ──
'camaradeputados': ('Afonso Florence (Dep. PT/BA)', -2),
'camaradosdeputados': ('Afonso Florence (Dep. PT/BA)', -2),
    'camaradeputados': ('Airton Faleiro (Dep. PT/PA)', -2),
    'camaradosdeputados': ('Airton Faleiro (Dep. PT/PA)', -2),
    'camaradeputados': ('Alencar Santana (Dep. PT/SP)', -2),
    'camaradosdeputados': ('Alencar Santana (Dep. PT/SP)', -2),
    'camaradeputados': ('Alexandre Lindenmeyer (Dep. PT/RS)', -2),
    'camaradosdeputados': ('Alexandre Lindenmeyer (Dep. PT/RS)', -2),
    'camaradeputados': ('Alfredinho (Dep. PT/SP)', -2),
    'camaradosdeputados': ('Alfredinho (Dep. PT/SP)', -2),
    'camaradeputados': ('Alice Portugal (Dep. PCdoB/BA)', -2),
    'camaradosdeputados': ('Alice Portugal (Dep. PCdoB/BA)', -2),
    'camaradeputados': ('Ana Paula Lima (Dep. PT/SC)', -2),
    'camaradosdeputados': ('Ana Paula Lima (Dep. PT/SC)', -2),
    'camaradeputados': ('Ana Pimentel (Dep. PT/MG)', -2),
    'camaradosdeputados': ('Ana Pimentel (Dep. PT/MG)', -2),
    'camaradeputados': ('Arlindo Chinaglia (Dep. PT/SP)', -2),
    'camaradosdeputados': ('Arlindo Chinaglia (Dep. PT/SP)', -2),
    'camaradeputados': ('Benedita da Silva (Dep. PT/RJ)', -2),
    'camaradosdeputados': ('Benedita da Silva (Dep. PT/RJ)', -2),
    'camaradeputados': ('Bohn Gass (Dep. PT/RS)', -2),
    'camaradosdeputados': ('Bohn Gass (Dep. PT/RS)', -2),
    'camaradeputados': ('Camila Jara (Dep. PT/MS)', -2),
    'camaradosdeputados': ('Camila Jara (Dep. PT/MS)', -2),
    'camaradeputados': ('Carlos Veras (Dep. PT/PE)', -2),
    'camaradosdeputados': ('Carlos Veras (Dep. PT/PE)', -2),
    'camaradeputados': ('Carlos Zarattini (Dep. PT/SP)', -2),
    'camaradosdeputados': ('Carlos Zarattini (Dep. PT/SP)', -2),
    'camaradeputados': ('Carol Dartora (Dep. PT/PR)', -2),
    'camaradosdeputados': ('Carol Dartora (Dep. PT/PR)', -2),
    'camaradeputados': ('Chico Alencar (Dep. PSOL/RJ)', -2),
    'camaradosdeputados': ('Chico Alencar (Dep. PSOL/RJ)', -2),
    'camaradeputados': ('Célia Xakriabá (Dep. PSOL/MG)', -2),
    'camaradosdeputados': ('Célia Xakriabá (Dep. PSOL/MG)', -2),
    'camaradeputados': ('Daiana Santos (Dep. PCdoB/RS)', -2),
    'camaradosdeputados': ('Daiana Santos (Dep. PCdoB/RS)', -2),
    'camaradeputados': ('Dandara (Dep. PT/MG)', -2),
    'camaradosdeputados': ('Dandara (Dep. PT/MG)', -2),
    'camaradeputados': ('Daniel Almeida (Dep. PCdoB/BA)', -2),
    'camaradosdeputados': ('Daniel Almeida (Dep. PCdoB/BA)', -2),
    'camaradeputados': ('Delegada Adriana Accorsi (Dep. PT/GO)', -2),
    'camaradosdeputados': ('Delegada Adriana Accorsi (Dep. PT/GO)', -2),
    'camaradeputados': ('Denise Pessôa (Dep. PT/RS)', -2),
    'camaradosdeputados': ('Denise Pessôa (Dep. PT/RS)', -2),
    'camaradeputados': ('Dilvanda Faro (Dep. PT/PA)', -2),
    'camaradosdeputados': ('Dilvanda Faro (Dep. PT/PA)', -2),
    'camaradeputados': ('Dimas Gadelha (Dep. PT/RJ)', -2),
    'camaradosdeputados': ('Dimas Gadelha (Dep. PT/RJ)', -2),
    'camaradeputados': ('Dr. Francisco (Dep. PT/PI)', -2),
    'camaradosdeputados': ('Dr. Francisco (Dep. PT/PI)', -2),
    'camaradeputados': ('Duda Salabert (Dep. PSOL/MG)', -2),
    'camaradosdeputados': ('Duda Salabert (Dep. PSOL/MG)', -2),
    'camaradeputados': ('Enfermeira Rejane (Dep. PCdoB/RJ)', -2),
    'camaradosdeputados': ('Enfermeira Rejane (Dep. PCdoB/RJ)', -2),
    'camaradeputados': ('Erika Hilton (Dep. PSOL/SP)', -2),
    'camaradosdeputados': ('Erika Hilton (Dep. PSOL/SP)', -2),
    'camaradeputados': ('Erika Kokay (Dep. PT/DF)', -2),
    'camaradosdeputados': ('Erika Kokay (Dep. PT/DF)', -2),
    'camaradeputados': ('Fernanda Melchionna (Dep. PSOL/RS)', -2),
    'camaradosdeputados': ('Fernanda Melchionna (Dep. PSOL/RS)', -2),
    'camaradeputados': ('Fernando Mineiro (Dep. PT/RN)', -2),
    'camaradosdeputados': ('Fernando Mineiro (Dep. PT/RN)', -2),
    'camaradeputados': ('Florentino Neto (Dep. PT/PI)', -2),
    'camaradosdeputados': ('Florentino Neto (Dep. PT/PI)', -2),
    'camaradeputados': ('Flávio Nogueira (Dep. PT/PI)', -2),
    'camaradosdeputados': ('Flávio Nogueira (Dep. PT/PI)', -2),
    'camaradeputados': ('Gervásio Maia (Dep. PCdoB/PB)', -2),
    'camaradosdeputados': ('Gervásio Maia (Dep. PCdoB/PB)', -2),
    'camaradeputados': ('Gleisi Hoffmann (Dep. PT/PR)', -2),
    'camaradosdeputados': ('Gleisi Hoffmann (Dep. PT/PR)', -2),
    'camaradeputados': ('Helder Salomão (Dep. PT/ES)', -2),
    'camaradosdeputados': ('Helder Salomão (Dep. PT/ES)', -2),
    'camaradeputados': ('Ivoneide Caetano (Dep. PT/BA)', -2),
    'camaradosdeputados': ('Ivoneide Caetano (Dep. PT/BA)', -2),
    'camaradeputados': ('Jack Rocha (Dep. PT/ES)', -2),
    'camaradosdeputados': ('Jack Rocha (Dep. PT/ES)', -2),
    'camaradeputados': ('Jandira Feghali (Dep. PCdoB/RJ)', -2),
    'camaradosdeputados': ('Jandira Feghali (Dep. PCdoB/RJ)', -2),
    'camaradeputados': ('Jilmar Tatto (Dep. PT/SP)', -2),
    'camaradosdeputados': ('Jilmar Tatto (Dep. PT/SP)', -2),
    'camaradeputados': ('Jorge Solla (Dep. PT/BA)', -2),
    'camaradosdeputados': ('Jorge Solla (Dep. PT/BA)', -2),
    'camaradeputados': ('Joseildo Ramos (Dep. PT/BA)', -2),
    'camaradosdeputados': ('Joseildo Ramos (Dep. PT/BA)', -2),
    'camaradeputados': ('José Airton Félix Cirilo (Dep. PT/CE)', -2),
    'camaradosdeputados': ('José Airton Félix Cirilo (Dep. PT/CE)', -2),
    'camaradeputados': ('José Guimarães (Dep. PT/CE)', -2),
    'camaradosdeputados': ('José Guimarães (Dep. PT/CE)', -2),
    'camaradeputados': ('João Daniel (Dep. PT/SE)', -2),
    'camaradosdeputados': ('João Daniel (Dep. PT/SE)', -2),
    'camaradeputados': ('Juliana Cardoso (Dep. PT/SP)', -2),
    'camaradosdeputados': ('Juliana Cardoso (Dep. PT/SP)', -2),
    'camaradeputados': ('Kiko Celeguim (Dep. PT/SP)', -2),
    'camaradosdeputados': ('Kiko Celeguim (Dep. PT/SP)', -2),
    'camaradeputados': ('Leonardo Monteiro (Dep. PT/MG)', -2),
    'camaradosdeputados': ('Leonardo Monteiro (Dep. PT/MG)', -2),
    'camaradeputados': ('Lindbergh Farias (Dep. PT/RJ)', -2),
    'camaradosdeputados': ('Lindbergh Farias (Dep. PT/RJ)', -2),
    'camaradeputados': ('Luiz Couto (Dep. PT/PB)', -2),
    'camaradosdeputados': ('Luiz Couto (Dep. PT/PB)', -2),
    'camaradeputados': ('Luiza Erundina (Dep. PSOL/SP)', -2),
    'camaradosdeputados': ('Luiza Erundina (Dep. PSOL/SP)', -2),
    'camaradeputados': ('Marcon (Dep. PT/RS)', -2),
    'camaradosdeputados': ('Marcon (Dep. PT/RS)', -2),
    'camaradeputados': ('Maria do Rosário (Dep. PT/RS)', -2),
    'camaradosdeputados': ('Maria do Rosário (Dep. PT/RS)', -2),
    'camaradeputados': ('Merlong Solano (Dep. PT/PI)', -2),
    'camaradosdeputados': ('Merlong Solano (Dep. PT/PI)', -2),
    'camaradeputados': ('Miguel Ângelo (Dep. PT/MG)', -2),
    'camaradosdeputados': ('Miguel Ângelo (Dep. PT/MG)', -2),
    'camaradeputados': ('Márcio Jerry (Dep. PCdoB/MA)', -2),
    'camaradosdeputados': ('Márcio Jerry (Dep. PCdoB/MA)', -2),
    'camaradeputados': ('Natália Bonavides (Dep. PT/RN)', -2),
    'camaradosdeputados': ('Natália Bonavides (Dep. PT/RN)', -2),
    'camaradeputados': ('Nilto Tatto (Dep. PT/SP)', -2),
    'camaradosdeputados': ('Nilto Tatto (Dep. PT/SP)', -2),
    'camaradeputados': ('Odair Cunha (Dep. PT/MG)', -2),
    'camaradosdeputados': ('Odair Cunha (Dep. PT/MG)', -2),
    'camaradeputados': ('Orlando Silva (Dep. PCdoB/SP)', -2),
    'camaradosdeputados': ('Orlando Silva (Dep. PCdoB/SP)', -2),
    'camaradeputados': ('Padre João (Dep. PT/MG)', -2),
    'camaradosdeputados': ('Padre João (Dep. PT/MG)', -2),
    'camaradeputados': ('Pastor Henrique Vieira (Dep. PSOL/RJ)', -2),
    'camaradosdeputados': ('Pastor Henrique Vieira (Dep. PSOL/RJ)', -2),
    'camaradeputados': ('Patrus Ananias (Dep. PT/MG)', -2),
    'camaradosdeputados': ('Patrus Ananias (Dep. PT/MG)', -2),
    'camaradeputados': ('Paulo Guedes (Dep. PT/MG)', -2),
    'camaradosdeputados': ('Paulo Guedes (Dep. PT/MG)', -2),
    'camaradeputados': ('Paulo Lemos (Dep. PT/AP)', -2),
    'camaradosdeputados': ('Paulo Lemos (Dep. PT/AP)', -2),
    'camaradeputados': ('Paulo Pimenta (Dep. PT/RS)', -2),
    'camaradosdeputados': ('Paulo Pimenta (Dep. PT/RS)', -2),
    'camaradeputados': ('Paulo Teixeira (Dep. PT/SP)', -2),
    'camaradosdeputados': ('Paulo Teixeira (Dep. PT/SP)', -2),
    'camaradeputados': ('Paulão (Dep. PT/AL)', -2),
    'camaradosdeputados': ('Paulão (Dep. PT/AL)', -2),
    'camaradeputados': ('Pedro Uczai (Dep. PT/SC)', -2),
    'camaradosdeputados': ('Pedro Uczai (Dep. PT/SC)', -2),
    'camaradeputados': ('Professora Luciene Cavalcante (Dep. PSOL/SP)', -2),
    'camaradosdeputados': ('Professora Luciene Cavalcante (Dep. PSOL/SP)', -2),
    'camaradeputados': ('Professora Marcivania (Dep. PCdoB/AP)', -2),
    'camaradosdeputados': ('Professora Marcivania (Dep. PCdoB/AP)', -2),
    'camaradeputados': ('Reginaldo Lopes (Dep. PT/MG)', -2),
    'camaradosdeputados': ('Reginaldo Lopes (Dep. PT/MG)', -2),
    'camaradeputados': ('Reimont (Dep. PT/RJ)', -2),
    'camaradosdeputados': ('Reimont (Dep. PT/RJ)', -2),
    'camaradeputados': ('Renildo Calheiros (Dep. PCdoB/PE)', -2),
    'camaradosdeputados': ('Renildo Calheiros (Dep. PCdoB/PE)', -2),
    'camaradeputados': ('Rogério Correia (Dep. PT/MG)', -2),
    'camaradosdeputados': ('Rogério Correia (Dep. PT/MG)', -2),
    'camaradeputados': ('Rubens Otoni (Dep. PT/GO)', -2),
    'camaradosdeputados': ('Rubens Otoni (Dep. PT/GO)', -2),
    'camaradeputados': ('Rubens Pereira Júnior (Dep. PT/MA)', -2),
    'camaradosdeputados': ('Rubens Pereira Júnior (Dep. PT/MA)', -2),
    'camaradeputados': ('Rui Falcão (Dep. PT/SP)', -2),
    'camaradosdeputados': ('Rui Falcão (Dep. PT/SP)', -2),
    'camaradeputados': ('Sâmia Bomfim (Dep. PSOL/SP)', -2),
    'camaradosdeputados': ('Sâmia Bomfim (Dep. PSOL/SP)', -2),
    'camaradeputados': ('Sônia Guajajara (Dep. PSOL/SP)', -2),
    'camaradosdeputados': ('Sônia Guajajara (Dep. PSOL/SP)', -2),
    'camaradeputados': ('Tadeu Veneri (Dep. PT/PR)', -2),
    'camaradosdeputados': ('Tadeu Veneri (Dep. PT/PR)', -2),
    'camaradeputados': ('Talíria Petrone (Dep. PSOL/RJ)', -2),
    'camaradosdeputados': ('Talíria Petrone (Dep. PSOL/RJ)', -2),
    'camaradeputados': ('Tarcísio Motta (Dep. PSOL/RJ)', -2),
    'camaradosdeputados': ('Tarcísio Motta (Dep. PSOL/RJ)', -2),
    'camaradeputados': ('Valmir Assunção (Dep. PT/BA)', -2),
    'camaradosdeputados': ('Valmir Assunção (Dep. PT/BA)', -2),
    'camaradeputados': ('Vander Loubet (Dep. PT/MS)', -2),
    'camaradosdeputados': ('Vander Loubet (Dep. PT/MS)', -2),
    'camaradeputados': ('Waldenor Pereira (Dep. PT/BA)', -2),
    'camaradosdeputados': ('Waldenor Pereira (Dep. PT/BA)', -2),
    'camaradeputados': ('Welter (Dep. PT/PR)', -2),
    'camaradosdeputados': ('Welter (Dep. PT/PR)', -2),
    'camaradeputados': ('Zeca Dirceu (Dep. PT/PR)', -2),
    'camaradosdeputados': ('Zeca Dirceu (Dep. PT/PR)', -2),
    'camaradeputados': ('Zé Neto (Dep. PT/BA)', -2),
    'camaradosdeputados': ('Zé Neto (Dep. PT/BA)', -2),

    # ── DEPUTADOS CENTRO-ESQUERDA (-1) ──
    'camaradeputados': ('Afonso Motta (Dep. PDT/RS)', -1),
    'camaradosdeputados': ('Afonso Motta (Dep. PDT/RS)', -1),
    'camaradeputados': ('Andreia Siqueira (Dep. PSB/PA)', -1),
    'camaradosdeputados': ('Andreia Siqueira (Dep. PSB/PA)', -1),
    'camaradeputados': ('André Figueiredo (Dep. PDT/CE)', -1),
    'camaradosdeputados': ('André Figueiredo (Dep. PDT/CE)', -1),
    'camaradeputados': ('André Janones (Dep. REDE/MG)', -1),
    'camaradosdeputados': ('André Janones (Dep. REDE/MG)', -1),
    'camaradeputados': ('Aureo Ribeiro (Dep. SOLIDARIEDADE/RJ)', -1),
    'camaradosdeputados': ('Aureo Ribeiro (Dep. SOLIDARIEDADE/RJ)', -1),
    'camaradeputados': ('Dorinaldo Malafaia (Dep. PDT/AP)', -1),
    'camaradosdeputados': ('Dorinaldo Malafaia (Dep. PDT/AP)', -1),
    'camaradeputados': ('Eduardo Velloso (Dep. SOLIDARIEDADE/AC)', -1),
    'camaradosdeputados': ('Eduardo Velloso (Dep. SOLIDARIEDADE/AC)', -1),
    'camaradeputados': ('Eriberto Medeiros (Dep. PSB/PE)', -1),
    'camaradosdeputados': ('Eriberto Medeiros (Dep. PSB/PE)', -1),
    'camaradeputados': ('Felipe Carreras (Dep. PSB/PE)', -1),
    'camaradosdeputados': ('Felipe Carreras (Dep. PSB/PE)', -1),
    'camaradeputados': ('Flávia Morais (Dep. PDT/GO)', -1),
    'camaradosdeputados': ('Flávia Morais (Dep. PDT/GO)', -1),
    'camaradeputados': ('Félix Mendonça Júnior (Dep. PDT/BA)', -1),
    'camaradosdeputados': ('Félix Mendonça Júnior (Dep. PDT/BA)', -1),
    'camaradeputados': ('Heloísa Helena (Dep. REDE/RJ)', -1),
    'camaradosdeputados': ('Heloísa Helena (Dep. REDE/RJ)', -1),
    'camaradeputados': ('Idilvan Alencar (Dep. PSB/CE)', -1),
    'camaradosdeputados': ('Idilvan Alencar (Dep. PSB/CE)', -1),
    'camaradeputados': ('Jonas Donizette (Dep. PSB/SP)', -1),
    'camaradosdeputados': ('Jonas Donizette (Dep. PSB/SP)', -1),
    'camaradeputados': ('Josenildo (Dep. PDT/AP)', -1),
    'camaradosdeputados': ('Josenildo (Dep. PDT/AP)', -1),
    'camaradeputados': ('Júnior Mano (Dep. PSB/CE)', -1),
    'camaradosdeputados': ('Júnior Mano (Dep. PSB/CE)', -1),
    'camaradeputados': ('Leo Prates (Dep. PDT/BA)', -1),
    'camaradosdeputados': ('Leo Prates (Dep. PDT/BA)', -1),
    'camaradeputados': ('Lucas Ramos (Dep. PSB/PE)', -1),
    'camaradosdeputados': ('Lucas Ramos (Dep. PSB/PE)', -1),
    'camaradeputados': ('Luciano Ducci (Dep. PSB/PR)', -1),
    'camaradosdeputados': ('Luciano Ducci (Dep. PSB/PR)', -1),
    'camaradeputados': ('Luizianne Lins (Dep. REDE/CE)', -1),
    'camaradosdeputados': ('Luizianne Lins (Dep. REDE/CE)', -1),
    'camaradeputados': ('Lídice da Mata (Dep. PSB/BA)', -1),
    'camaradosdeputados': ('Lídice da Mata (Dep. PSB/BA)', -1),
    'camaradeputados': ('Marcos Tavares (Dep. PDT/RJ)', -1),
    'camaradosdeputados': ('Marcos Tavares (Dep. PDT/RJ)', -1),
    'camaradeputados': ('Maria Arraes (Dep. PSB/PE)', -1),
    'camaradosdeputados': ('Maria Arraes (Dep. PSB/PE)', -1),
    'camaradeputados': ('Marina Silva (Dep. REDE/SP)', -1),
    'camaradosdeputados': ('Marina Silva (Dep. REDE/SP)', -1),
    'camaradeputados': ('Max Lemos (Dep. PDT/RJ)', -1),
    'camaradosdeputados': ('Max Lemos (Dep. PDT/RJ)', -1),
    'camaradeputados': ('Márcio Honaiser (Dep. PDT/MA)', -1),
    'camaradosdeputados': ('Márcio Honaiser (Dep. PDT/MA)', -1),
    'camaradeputados': ('Mário Heringer (Dep. PDT/MG)', -1),
    'camaradosdeputados': ('Mário Heringer (Dep. PDT/MG)', -1),
    'camaradeputados': ('Mário Negromonte Jr. (Dep. PSB/BA)', -1),
    'camaradosdeputados': ('Mário Negromonte Jr. (Dep. PSB/BA)', -1),
    'camaradeputados': ('Paulinho da Força (Dep. SOLIDARIEDADE/SP)', -1),
    'camaradosdeputados': ('Paulinho da Força (Dep. SOLIDARIEDADE/SP)', -1),
    'camaradeputados': ('Paulo Folletto (Dep. PSB/ES)', -1),
    'camaradosdeputados': ('Paulo Folletto (Dep. PSB/ES)', -1),
    'camaradeputados': ('Pedro Campos (Dep. PSB/PE)', -1),
    'camaradosdeputados': ('Pedro Campos (Dep. PSB/PE)', -1),
    'camaradeputados': ('Pompeo de Mattos (Dep. PDT/RS)', -1),
    'camaradosdeputados': ('Pompeo de Mattos (Dep. PDT/RS)', -1),
    'camaradeputados': ('Ribeiro Neto (Dep. SOLIDARIEDADE/MA)', -1),
    'camaradosdeputados': ('Ribeiro Neto (Dep. SOLIDARIEDADE/MA)', -1),
    'camaradeputados': ('Robério Monteiro (Dep. PSB/CE)', -1),
    'camaradosdeputados': ('Robério Monteiro (Dep. PSB/CE)', -1),
    'camaradeputados': ('Rodrigo Rollemberg (Dep. PSB/DF)', -1),
    'camaradosdeputados': ('Rodrigo Rollemberg (Dep. PSB/DF)', -1),
    'camaradeputados': ('Tabata Amaral (Dep. PSB/SP)', -1),
    'camaradosdeputados': ('Tabata Amaral (Dep. PSB/SP)', -1),
    'camaradeputados': ('Vanderlan Alves (Dep. SOLIDARIEDADE/CE)', -1),
    'camaradosdeputados': ('Vanderlan Alves (Dep. SOLIDARIEDADE/CE)', -1),
    'camaradeputados': ('Weliton Prado (Dep. SOLIDARIEDADE/MG)', -1),
    'camaradosdeputados': ('Weliton Prado (Dep. SOLIDARIEDADE/MG)', -1),

    # ── DEPUTADOS CENTRO (0) ──
    'camaradeputados': ('Acácio Favacho (Dep. MDB/AP)', 0),
    'camaradosdeputados': ('Acácio Favacho (Dep. MDB/AP)', 0),
    'camaradeputados': ('Adail Filho (Dep. MDB/AM)', 0),
    'camaradosdeputados': ('Adail Filho (Dep. MDB/AM)', 0),
    'camaradeputados': ('Adolfo Viana (Dep. PSDB/BA)', 0),
    'camaradosdeputados': ('Adolfo Viana (Dep. PSDB/BA)', 0),
    'camaradeputados': ('Alceu Moreira (Dep. MDB/RS)', 0),
    'camaradosdeputados': ('Alceu Moreira (Dep. MDB/RS)', 0),
    'camaradeputados': ('Alex Manente (Dep. CIDADANIA/SP)', 0),
    'camaradosdeputados': ('Alex Manente (Dep. CIDADANIA/SP)', 0),
    'camaradeputados': ('Alexandre Guimarães (Dep. MDB/TO)', 0),
    'camaradosdeputados': ('Alexandre Guimarães (Dep. MDB/TO)', 0),
    'camaradeputados': ('Aliel Machado (Dep. PV/PR)', 0),
    'camaradosdeputados': ('Aliel Machado (Dep. PV/PR)', 0),
    'camaradeputados': ('Antonio Brito (Dep. PSD/BA)', 0),
    'camaradosdeputados': ('Antonio Brito (Dep. PSD/BA)', 0),
    'camaradeputados': ('Antônia Lúcia (Dep. MDB/AC)', 0),
    'camaradosdeputados': ('Antônia Lúcia (Dep. MDB/AC)', 0),
    'camaradeputados': ('Antônio Doido (Dep. MDB/PA)', 0),
    'camaradosdeputados': ('Antônio Doido (Dep. MDB/PA)', 0),
    'camaradeputados': ('Any Ortiz (Dep. CIDADANIA/RS)', 0),
    'camaradosdeputados': ('Any Ortiz (Dep. CIDADANIA/RS)', 0),
    'camaradeputados': ('Arnaldo Jardim (Dep. CIDADANIA/SP)', 0),
    'camaradosdeputados': ('Arnaldo Jardim (Dep. CIDADANIA/SP)', 0),
    'camaradeputados': ('Aécio Neves (Dep. PSDB/MG)', 0),
    'camaradosdeputados': ('Aécio Neves (Dep. PSDB/MG)', 0),
    'camaradeputados': ('Bacelar (Dep. PV/BA)', 0),
    'camaradosdeputados': ('Bacelar (Dep. PV/BA)', 0),
    'camaradeputados': ('Baleia Rossi (Dep. MDB/SP)', 0),
    'camaradosdeputados': ('Baleia Rossi (Dep. MDB/SP)', 0),
    'camaradeputados': ('Bandeira de Mello (Dep. PV/RJ)', 0),
    'camaradosdeputados': ('Bandeira de Mello (Dep. PV/RJ)', 0),
    'camaradeputados': ('Beto Preto (Dep. PSD/PR)', 0),
    'camaradosdeputados': ('Beto Preto (Dep. PSD/PR)', 0),
    'camaradeputados': ('Beto Richa (Dep. PSDB/PR)', 0),
    'camaradosdeputados': ('Beto Richa (Dep. PSDB/PR)', 0),
    'camaradeputados': ('Carlos Chiodini (Dep. MDB/SC)', 0),
    'camaradosdeputados': ('Carlos Chiodini (Dep. MDB/SC)', 0),
    'camaradeputados': ('Carlos Sampaio (Dep. PSD/SP)', 0),
    'camaradosdeputados': ('Carlos Sampaio (Dep. PSD/SP)', 0),
    'camaradeputados': ('Castro Neto (Dep. MDB/PI)', 0),
    'camaradosdeputados': ('Castro Neto (Dep. MDB/PI)', 0),
    'camaradeputados': ('Charles Fernandes (Dep. PSD/BA)', 0),
    'camaradosdeputados': ('Charles Fernandes (Dep. PSD/BA)', 0),
    'camaradeputados': ('Cleber Verde (Dep. MDB/MA)', 0),
    'camaradosdeputados': ('Cleber Verde (Dep. MDB/MA)', 0),
    'camaradeputados': ('Clodoaldo Magalhães (Dep. PV/PE)', 0),
    'camaradosdeputados': ('Clodoaldo Magalhães (Dep. PV/PE)', 0),
    'camaradeputados': ('Cobalchini (Dep. MDB/SC)', 0),
    'camaradosdeputados': ('Cobalchini (Dep. MDB/SC)', 0),
    'camaradeputados': ('Célio Silveira (Dep. MDB/GO)', 0),
    'camaradosdeputados': ('Célio Silveira (Dep. MDB/GO)', 0),
    'camaradeputados': ('Célio Studart (Dep. PSD/CE)', 0),
    'camaradosdeputados': ('Célio Studart (Dep. PSD/CE)', 0),
    'camaradeputados': ('Daniel Trzeciak (Dep. PSDB/RS)', 0),
    'camaradosdeputados': ('Daniel Trzeciak (Dep. PSDB/RS)', 0),
    'camaradeputados': ('Danrlei de Deus Hinterholz (Dep. PSD/RS)', 0),
    'camaradosdeputados': ('Danrlei de Deus Hinterholz (Dep. PSD/RS)', 0),
    'camaradeputados': ('Delegada Ione (Dep. AVANTE/MG)', 0),
    'camaradosdeputados': ('Delegada Ione (Dep. AVANTE/MG)', 0),
    'camaradeputados': ('Delegada Katarina (Dep. PSD/SE)', 0),
    'camaradosdeputados': ('Delegada Katarina (Dep. PSD/SE)', 0),
    'camaradeputados': ('Diego Andrade (Dep. PSD/MG)', 0),
    'camaradosdeputados': ('Diego Andrade (Dep. PSD/MG)', 0),
    'camaradeputados': ('Domingos Neto (Dep. PSD/CE)', 0),
    'camaradosdeputados': ('Domingos Neto (Dep. PSD/CE)', 0),
    'camaradeputados': ('Dr. Daniel Soranz (Dep. PSD/RJ)', 0),
    'camaradosdeputados': ('Dr. Daniel Soranz (Dep. PSD/RJ)', 0),
    'camaradeputados': ('Dr. Frederico (Dep. PRD/MG)', 0),
    'camaradosdeputados': ('Dr. Frederico (Dep. PRD/MG)', 0),
    'camaradeputados': ('Dr. Ismael Alexandrino (Dep. PSD/GO)', 0),
    'camaradosdeputados': ('Dr. Ismael Alexandrino (Dep. PSD/GO)', 0),
    'camaradeputados': ('Duarte Jr. (Dep. AVANTE/MA)', 0),
    'camaradosdeputados': ('Duarte Jr. (Dep. AVANTE/MA)', 0),
    'camaradeputados': ('Duda Ramos (Dep. MDB/RR)', 0),
    'camaradosdeputados': ('Duda Ramos (Dep. MDB/RR)', 0),
    'camaradeputados': ('Eduardo Bismarck (Dep. PV/CE)', 0),
    'camaradosdeputados': ('Eduardo Bismarck (Dep. PV/CE)', 0),
    'camaradeputados': ('Elcione Barbalho (Dep. MDB/PA)', 0),
    'camaradosdeputados': ('Elcione Barbalho (Dep. MDB/PA)', 0),
    'camaradeputados': ('Emanuel Pinheiro Neto (Dep. PSD/MT)', 0),
    'camaradosdeputados': ('Emanuel Pinheiro Neto (Dep. PSD/MT)', 0),
    'camaradeputados': ('Eunício Oliveira (Dep. MDB/CE)', 0),
    'camaradosdeputados': ('Eunício Oliveira (Dep. MDB/CE)', 0),
    'camaradeputados': ('Fabio Reis (Dep. PSD/SE)', 0),
    'camaradosdeputados': ('Fabio Reis (Dep. PSD/SE)', 0),
    'camaradeputados': ('Fernanda Pessoa (Dep. PSD/CE)', 0),
    'camaradosdeputados': ('Fernanda Pessoa (Dep. PSD/CE)', 0),
    'camaradeputados': ('Fernando Monteiro (Dep. PSD/PE)', 0),
    'camaradosdeputados': ('Fernando Monteiro (Dep. PSD/PE)', 0),
    'camaradeputados': ('Fernando Rodolfo (Dep. PRD/PE)', 0),
    'camaradosdeputados': ('Fernando Rodolfo (Dep. PRD/PE)', 0),
    'camaradeputados': ('Fred Costa (Dep. PRD/MG)', 0),
    'camaradosdeputados': ('Fred Costa (Dep. PRD/MG)', 0),
    'camaradeputados': ('Fábio Teruel (Dep. MDB/SP)', 0),
    'camaradosdeputados': ('Fábio Teruel (Dep. MDB/SP)', 0),
    'camaradeputados': ('Gabriel Nunes (Dep. PSD/BA)', 0),
    'camaradosdeputados': ('Gabriel Nunes (Dep. PSD/BA)', 0),
    'camaradeputados': ('Geovania de Sá (Dep. PSDB/SC)', 0),
    'camaradosdeputados': ('Geovania de Sá (Dep. PSDB/SC)', 0),
    'camaradeputados': ('Geraldo Resende (Dep. PSDB/MS)', 0),
    'camaradosdeputados': ('Geraldo Resende (Dep. PSDB/MS)', 0),
    'camaradeputados': ('Giacobo (Dep. PSD/PR)', 0),
    'camaradosdeputados': ('Giacobo (Dep. PSD/PR)', 0),
    'camaradeputados': ('Gilberto Nascimento (Dep. PSD/SP)', 0),
    'camaradosdeputados': ('Gilberto Nascimento (Dep. PSD/SP)', 0),
    'camaradeputados': ('Gorete Pereira (Dep. MDB/CE)', 0),
    'camaradosdeputados': ('Gorete Pereira (Dep. MDB/CE)', 0),
    'camaradeputados': ('Greyce Elias (Dep. AVANTE/MG)', 0),
    'camaradosdeputados': ('Greyce Elias (Dep. AVANTE/MG)', 0),
    'camaradeputados': ('Guilherme Uchoa (Dep. PSD/PE)', 0),
    'camaradosdeputados': ('Guilherme Uchoa (Dep. PSD/PE)', 0),
    'camaradeputados': ('Gutemberg Reis (Dep. MDB/RJ)', 0),
    'camaradosdeputados': ('Gutemberg Reis (Dep. MDB/RJ)', 0),
    'camaradeputados': ('Heitor Schuch (Dep. PSD/RS)', 0),
    'camaradosdeputados': ('Heitor Schuch (Dep. PSD/RS)', 0),
    'camaradeputados': ('Helena Lima (Dep. PSD/RR)', 0),
    'camaradosdeputados': ('Helena Lima (Dep. PSD/RR)', 0),
    'camaradeputados': ('Hercílio Coelho Diniz (Dep. MDB/MG)', 0),
    'camaradosdeputados': ('Hercílio Coelho Diniz (Dep. MDB/MG)', 0),
    'camaradeputados': ('Hildo Rocha (Dep. MDB/MA)', 0),
    'camaradosdeputados': ('Hildo Rocha (Dep. MDB/MA)', 0),
    'camaradeputados': ('Hugo Leal (Dep. PSD/RJ)', 0),
    'camaradosdeputados': ('Hugo Leal (Dep. PSD/RJ)', 0),
    'camaradeputados': ('Igor Timo (Dep. PSD/MG)', 0),
    'camaradosdeputados': ('Igor Timo (Dep. PSD/MG)', 0),
    'camaradeputados': ('Isnaldo Bulhões Jr. (Dep. MDB/AL)', 0),
    'camaradosdeputados': ('Isnaldo Bulhões Jr. (Dep. MDB/AL)', 0),
    'camaradeputados': ('Iza Arruda (Dep. MDB/PE)', 0),
    'camaradosdeputados': ('Iza Arruda (Dep. MDB/PE)', 0),
    'camaradeputados': ('Jeferson Rodrigues (Dep. PSDB/GO)', 0),
    'camaradosdeputados': ('Jeferson Rodrigues (Dep. PSDB/GO)', 0),
    'camaradeputados': ('Josivaldo JP (Dep. PSD/MA)', 0),
    'camaradosdeputados': ('Josivaldo JP (Dep. PSD/MA)', 0),
    'camaradeputados': ('José Priante (Dep. MDB/PA)', 0),
    'camaradosdeputados': ('José Priante (Dep. MDB/PA)', 0),
    'camaradeputados': ('João Cury (Dep. MDB/SP)', 0),
    'camaradosdeputados': ('João Cury (Dep. MDB/SP)', 0),
    'camaradeputados': ('Juninho do Pneu (Dep. PSDB/RJ)', 0),
    'camaradosdeputados': ('Juninho do Pneu (Dep. PSDB/RJ)', 0),
    'camaradeputados': ('Junior Lourenço (Dep. MDB/MA)', 0),
    'camaradosdeputados': ('Junior Lourenço (Dep. MDB/MA)', 0),
    'camaradeputados': ('Juscelino Filho (Dep. PSDB/MA)', 0),
    'camaradosdeputados': ('Juscelino Filho (Dep. PSDB/MA)', 0),
    'camaradeputados': ('Júlio Cesar (Dep. PSD/PI)', 0),
    'camaradosdeputados': ('Júlio Cesar (Dep. PSD/PI)', 0),
    'camaradeputados': ('Júnior Ferrari (Dep. PSD/PA)', 0),
    'camaradosdeputados': ('Júnior Ferrari (Dep. PSD/PA)', 0),
    'camaradeputados': ('Keniston Braga (Dep. MDB/PA)', 0),
    'camaradosdeputados': ('Keniston Braga (Dep. MDB/PA)', 0),
    'camaradeputados': ('Kim Kataguiri (Dep. MISSÃO/SP)', 0),
    'camaradosdeputados': ('Kim Kataguiri (Dep. MISSÃO/SP)', 0),
    'camaradeputados': ('Laura Carneiro (Dep. PSD/RJ)', 0),
    'camaradosdeputados': ('Laura Carneiro (Dep. PSD/RJ)', 0),
    'camaradeputados': ('Leandre (Dep. PSD/PR)', 0),
    'camaradosdeputados': ('Leandre (Dep. PSD/PR)', 0),
    'camaradeputados': ('Lucas Redecker (Dep. PSD/RS)', 0),
    'camaradosdeputados': ('Lucas Redecker (Dep. PSD/RS)', 0),
    'camaradeputados': ('Luciano Amaral (Dep. PSD/AL)', 0),
    'camaradosdeputados': ('Luciano Amaral (Dep. PSD/AL)', 0),
    'camaradeputados': ('Luciano Bivar (Dep. MDB/PE)', 0),
    'camaradosdeputados': ('Luciano Bivar (Dep. MDB/PE)', 0),
    'camaradeputados': ('Luciano Vieira (Dep. PSDB/RJ)', 0),
    'camaradosdeputados': ('Luciano Vieira (Dep. PSDB/RJ)', 0),
    'camaradeputados': ('Luisa Canziani (Dep. PSD/PR)', 0),
    'camaradosdeputados': ('Luisa Canziani (Dep. PSD/PR)', 0),
    'camaradeputados': ('Luiz Gastão (Dep. PSD/CE)', 0),
    'camaradosdeputados': ('Luiz Gastão (Dep. PSD/CE)', 0),
    'camaradeputados': ('Luiz Nishimori (Dep. PSD/PR)', 0),
    'camaradosdeputados': ('Luiz Nishimori (Dep. PSD/PR)', 0),
    'camaradeputados': ('Marcelo Queiroz (Dep. PSDB/RJ)', 0),
    'camaradosdeputados': ('Marcelo Queiroz (Dep. PSDB/RJ)', 0),
    'camaradeputados': ('Marcos Aurélio Sampaio (Dep. MDB/PI)', 0),
    'camaradosdeputados': ('Marcos Aurélio Sampaio (Dep. MDB/PI)', 0),
    'camaradeputados': ('Marcos Soares (Dep. PSDB/RJ)', 0),
    'camaradosdeputados': ('Marcos Soares (Dep. PSDB/RJ)', 0),
    'camaradeputados': ('Mersinho Lucena (Dep. PSD/PB)', 0),
    'camaradosdeputados': ('Mersinho Lucena (Dep. PSD/PB)', 0),
    'camaradeputados': ('Misael Varella (Dep. PSD/MG)', 0),
    'camaradosdeputados': ('Misael Varella (Dep. PSD/MG)', 0),
    'camaradeputados': ('Márcio Biolchi (Dep. MDB/RS)', 0),
    'camaradosdeputados': ('Márcio Biolchi (Dep. MDB/RS)', 0),
    'camaradeputados': ('Neto Carletto (Dep. AVANTE/BA)', 0),
    'camaradosdeputados': ('Neto Carletto (Dep. AVANTE/BA)', 0),
    'camaradeputados': ('Newton Cardoso Jr (Dep. MDB/MG)', 0),
    'camaradosdeputados': ('Newton Cardoso Jr (Dep. MDB/MG)', 0),
    'camaradeputados': ('Otoni de Paula (Dep. PSD/RJ)', 0),
    'camaradosdeputados': ('Otoni de Paula (Dep. PSD/RJ)', 0),
    'camaradeputados': ('Pastor Eurico (Dep. PSDB/PE)', 0),
    'camaradosdeputados': ('Pastor Eurico (Dep. PSDB/PE)', 0),
    'camaradeputados': ('Pastor Sargento Isidório (Dep. AVANTE/BA)', 0),
    'camaradosdeputados': ('Pastor Sargento Isidório (Dep. AVANTE/BA)', 0),
    'camaradeputados': ('Paulo Abi-Ackel (Dep. PSDB/MG)', 0),
    'camaradosdeputados': ('Paulo Abi-Ackel (Dep. PSDB/MG)', 0),
    'camaradeputados': ('Paulo Alexandre Barbosa (Dep. PSDB/SP)', 0),
    'camaradosdeputados': ('Paulo Alexandre Barbosa (Dep. PSDB/SP)', 0),
    'camaradeputados': ('Paulo Magalhães (Dep. PSD/BA)', 0),
    'camaradosdeputados': ('Paulo Magalhães (Dep. PSD/BA)', 0),
    'camaradeputados': ('Pedro Paulo (Dep. PSD/RJ)', 0),
    'camaradosdeputados': ('Pedro Paulo (Dep. PSD/RJ)', 0),
    'camaradeputados': ('Pezenti (Dep. MDB/SC)', 0),
    'camaradosdeputados': ('Pezenti (Dep. MDB/SC)', 0),
    'camaradeputados': ('Prof. Reginaldo Veras (Dep. PV/DF)', 0),
    'camaradosdeputados': ('Prof. Reginaldo Veras (Dep. PV/DF)', 0),
    'camaradeputados': ('Professor Alcides (Dep. PSDB/GO)', 0),
    'camaradosdeputados': ('Professor Alcides (Dep. PSDB/GO)', 0),
    'camaradeputados': ('Rafael Brito (Dep. MDB/AL)', 0),
    'camaradosdeputados': ('Rafael Brito (Dep. MDB/AL)', 0),
    'camaradeputados': ('Rafael Prudente (Dep. MDB/DF)', 0),
    'camaradosdeputados': ('Rafael Prudente (Dep. MDB/DF)', 0),
    'camaradeputados': ('Raimundo Costa (Dep. PSD/BA)', 0),
    'camaradosdeputados': ('Raimundo Costa (Dep. PSD/BA)', 0),
    'camaradeputados': ('Raimundo Santos (Dep. PSD/PA)', 0),
    'camaradosdeputados': ('Raimundo Santos (Dep. PSD/PA)', 0),
    'camaradeputados': ('Renilce Nicodemos (Dep. MDB/PA)', 0),
    'camaradosdeputados': ('Renilce Nicodemos (Dep. MDB/PA)', 0),
    'camaradeputados': ('Ribamar Silva (Dep. PSD/SP)', 0),
    'camaradosdeputados': ('Ribamar Silva (Dep. PSD/SP)', 0),
    'camaradeputados': ('Ricardo Abrão (Dep. PSDB/RJ)', 0),
    'camaradosdeputados': ('Ricardo Abrão (Dep. PSDB/RJ)', 0),
    'camaradeputados': ('Ricardo Maia (Dep. MDB/BA)', 0),
    'camaradosdeputados': ('Ricardo Maia (Dep. MDB/BA)', 0),
    'camaradeputados': ('Sandro Alex (Dep. PSD/PR)', 0),
    'camaradosdeputados': ('Sandro Alex (Dep. PSD/PR)', 0),
    'camaradeputados': ('Saullo Vianna (Dep. MDB/AM)', 0),
    'camaradosdeputados': ('Saullo Vianna (Dep. MDB/AM)', 0),
    'camaradeputados': ('Saulo Pedroso (Dep. PSD/SP)', 0),
    'camaradosdeputados': ('Saulo Pedroso (Dep. PSD/SP)', 0),
    'camaradeputados': ('Sergio Souza (Dep. MDB/PR)', 0),
    'camaradosdeputados': ('Sergio Souza (Dep. MDB/PR)', 0),
    'camaradeputados': ('Sidney Leite (Dep. PSD/AM)', 0),
    'camaradosdeputados': ('Sidney Leite (Dep. PSD/AM)', 0),
    'camaradeputados': ('Stefano Aguiar (Dep. PSD/MG)', 0),
    'camaradosdeputados': ('Stefano Aguiar (Dep. PSD/MG)', 0),
    'camaradeputados': ('Sérgio Brito (Dep. PSD/BA)', 0),
    'camaradosdeputados': ('Sérgio Brito (Dep. PSD/BA)', 0),
    'camaradeputados': ('Tiririca (Dep. PSD/SP)', 0),
    'camaradosdeputados': ('Tiririca (Dep. PSD/SP)', 0),
    'camaradeputados': ('Túlio Gadêlha (Dep. PSD/PE)', 0),
    'camaradosdeputados': ('Túlio Gadêlha (Dep. PSD/PE)', 0),
    'camaradeputados': ('Vavá (Dep. AVANTE/MG)', 0),
    'camaradosdeputados': ('Vavá (Dep. AVANTE/MG)', 0),
    'camaradeputados': ('Vicentinho Júnior (Dep. PSDB/TO)', 0),
    'camaradosdeputados': ('Vicentinho Júnior (Dep. PSDB/TO)', 0),
    'camaradeputados': ('Vitor Lippi (Dep. PSD/SP)', 0),
    'camaradosdeputados': ('Vitor Lippi (Dep. PSD/SP)', 0),
    'camaradeputados': ('Waldemar Oliveira (Dep. AVANTE/PE)', 0),
    'camaradosdeputados': ('Waldemar Oliveira (Dep. AVANTE/PE)', 0),
    'camaradeputados': ('Wellington Roberto (Dep. PSD/PB)', 0),
    'camaradosdeputados': ('Wellington Roberto (Dep. PSD/PB)', 0),
    'camaradeputados': ('Átila Lins (Dep. PSD/AM)', 0),
    'camaradosdeputados': ('Átila Lins (Dep. PSD/AM)', 0),

    # ── DEPUTADOS CENTRO-DIREITA (1) ──
    'camaradeputados': ('AJ Albuquerque (Dep. PP/CE)', 1),
    'camaradosdeputados': ('AJ Albuquerque (Dep. PP/CE)', 1),
    'camaradeputados': ('Adriana Ventura (Dep. NOVO/SP)', 1),
    'camaradosdeputados': ('Adriana Ventura (Dep. NOVO/SP)', 1),
    'camaradeputados': ('Adriano do Baldy (Dep. PP/GO)', 1),
    'camaradosdeputados': ('Adriano do Baldy (Dep. PP/GO)', 1),
    'camaradeputados': ('Afonso Hamm (Dep. PP/RS)', 1),
    'camaradosdeputados': ('Afonso Hamm (Dep. PP/RS)', 1),
    'camaradeputados': ('Aguinaldo Ribeiro (Dep. PP/PB)', 1),
    'camaradosdeputados': ('Aguinaldo Ribeiro (Dep. PP/PB)', 1),
    'camaradeputados': ('Albuquerque (Dep. REPUBLICANOS/RR)', 1),
    'camaradosdeputados': ('Albuquerque (Dep. REPUBLICANOS/RR)', 1),
    'camaradeputados': ('Alexandre Leite (Dep. UNIÃO/SP)', 1),
    'camaradosdeputados': ('Alexandre Leite (Dep. UNIÃO/SP)', 1),
    'camaradeputados': ('Alfredo Gaspar (Dep. UNIÃO/AL)', 1),
    'camaradosdeputados': ('Alfredo Gaspar (Dep. UNIÃO/AL)', 1),
    'camaradeputados': ('Aline Gurgel (Dep. UNIÃO/AP)', 1),
    'camaradosdeputados': ('Aline Gurgel (Dep. UNIÃO/AP)', 1),
    'camaradeputados': ('Aluisio Mendes (Dep. REPUBLICANOS/MA)', 1),
    'camaradosdeputados': ('Aluisio Mendes (Dep. REPUBLICANOS/MA)', 1),
    'camaradeputados': ('Amanda Gentil (Dep. PP/MA)', 1),
    'camaradosdeputados': ('Amanda Gentil (Dep. PP/MA)', 1),
    'camaradeputados': ('Amaro Neto (Dep. PP/ES)', 1),
    'camaradosdeputados': ('Amaro Neto (Dep. PP/ES)', 1),
    'camaradeputados': ('Amom Mandel (Dep. REPUBLICANOS/AM)', 1),
    'camaradosdeputados': ('Amom Mandel (Dep. REPUBLICANOS/AM)', 1),
    'camaradeputados': ('Ana Paula Leão (Dep. PP/MG)', 1),
    'camaradosdeputados': ('Ana Paula Leão (Dep. PP/MG)', 1),
    'camaradeputados': ('André Abdon (Dep. PP/AP)', 1),
    'camaradosdeputados': ('André Abdon (Dep. PP/AP)', 1),
    'camaradeputados': ('André Fufuca (Dep. PP/MA)', 1),
    'camaradosdeputados': ('André Fufuca (Dep. PP/MA)', 1),
    'camaradeputados': ('Antonio Andrade (Dep. REPUBLICANOS/TO)', 1),
    'camaradosdeputados': ('Antonio Andrade (Dep. REPUBLICANOS/TO)', 1),
    'camaradeputados': ('Arthur Lira (Dep. PP/AL)', 1),
    'camaradosdeputados': ('Arthur Lira (Dep. PP/AL)', 1),
    'camaradeputados': ('Arthur Oliveira Maia (Dep. UNIÃO/BA)', 1),
    'camaradosdeputados': ('Arthur Oliveira Maia (Dep. UNIÃO/BA)', 1),
    'camaradeputados': ('Augusto Coutinho (Dep. REPUBLICANOS/PE)', 1),
    'camaradosdeputados': ('Augusto Coutinho (Dep. REPUBLICANOS/PE)', 1),
    'camaradeputados': ('Bebeto (Dep. PP/RJ)', 1),
    'camaradosdeputados': ('Bebeto (Dep. PP/RJ)', 1),
    'camaradeputados': ('Benes Leocádio (Dep. UNIÃO/RN)', 1),
    'camaradosdeputados': ('Benes Leocádio (Dep. UNIÃO/RN)', 1),
    'camaradeputados': ('Beto Pereira (Dep. REPUBLICANOS/MS)', 1),
    'camaradosdeputados': ('Beto Pereira (Dep. REPUBLICANOS/MS)', 1),
    'camaradeputados': ('Bruno Farias (Dep. REPUBLICANOS/MG)', 1),
    'camaradosdeputados': ('Bruno Farias (Dep. REPUBLICANOS/MG)', 1),
    'camaradeputados': ('Bruno Ganem (Dep. PODE/SP)', 1),
    'camaradosdeputados': ('Bruno Ganem (Dep. PODE/SP)', 1),
    'camaradeputados': ('Carla Dickson (Dep. UNIÃO/RN)', 1),
    'camaradosdeputados': ('Carla Dickson (Dep. UNIÃO/RN)', 1),
    'camaradeputados': ('Carlos Gomes (Dep. REPUBLICANOS/RS)', 1),
    'camaradosdeputados': ('Carlos Gomes (Dep. REPUBLICANOS/RS)', 1),
    'camaradeputados': ('Carlos Henrique Gaguim (Dep. UNIÃO/TO)', 1),
    'camaradosdeputados': ('Carlos Henrique Gaguim (Dep. UNIÃO/TO)', 1),
    'camaradeputados': ('Celso Russomanno (Dep. REPUBLICANOS/SP)', 1),
    'camaradosdeputados': ('Celso Russomanno (Dep. REPUBLICANOS/SP)', 1),
    'camaradeputados': ('Celso Sabino (Dep. UNIÃO/PA)', 1),
    'camaradosdeputados': ('Celso Sabino (Dep. UNIÃO/PA)', 1),
    'camaradeputados': ('Clarissa Tércio (Dep. PP/PE)', 1),
    'camaradosdeputados': ('Clarissa Tércio (Dep. PP/PE)', 1),
    'camaradeputados': ('Claudio Cajado (Dep. PP/BA)', 1),
    'camaradosdeputados': ('Claudio Cajado (Dep. PP/BA)', 1),
    'camaradeputados': ('Coronel Ulysses (Dep. UNIÃO/AC)', 1),
    'camaradosdeputados': ('Coronel Ulysses (Dep. UNIÃO/AC)', 1),
    'camaradeputados': ('Cristiane Lopes (Dep. PODE/RO)', 1),
    'camaradosdeputados': ('Cristiane Lopes (Dep. PODE/RO)', 1),
    'camaradeputados': ('Da Vitoria (Dep. PP/ES)', 1),
    'camaradosdeputados': ('Da Vitoria (Dep. PP/ES)', 1),
    'camaradeputados': ('Dagoberto Nogueira (Dep. PP/MS)', 1),
    'camaradosdeputados': ('Dagoberto Nogueira (Dep. PP/MS)', 1),
    'camaradeputados': ('Dal Barreto (Dep. UNIÃO/BA)', 1),
    'camaradosdeputados': ('Dal Barreto (Dep. UNIÃO/BA)', 1),
    'camaradeputados': ('Damião Feliciano (Dep. UNIÃO/PB)', 1),
    'camaradosdeputados': ('Damião Feliciano (Dep. UNIÃO/PB)', 1),
    'camaradeputados': ('Daniel Barbosa (Dep. PP/AL)', 1),
    'camaradosdeputados': ('Daniel Barbosa (Dep. PP/AL)', 1),
    'camaradeputados': ('Daniela do Waguinho (Dep. REPUBLICANOS/RJ)', 1),
    'camaradosdeputados': ('Daniela do Waguinho (Dep. REPUBLICANOS/RJ)', 1),
    'camaradeputados': ('Danilo Forte (Dep. PP/CE)', 1),
    'camaradosdeputados': ('Danilo Forte (Dep. PP/CE)', 1),
    'camaradeputados': ('David Soares (Dep. PODE/SP)', 1),
    'camaradosdeputados': ('David Soares (Dep. PODE/SP)', 1),
    'camaradeputados': ('Defensor Stélio Dener (Dep. UNIÃO/RR)', 1),
    'camaradosdeputados': ('Defensor Stélio Dener (Dep. UNIÃO/RR)', 1),
    'camaradeputados': ('Delegado Bruno Lima (Dep. PODE/SP)', 1),
    'camaradosdeputados': ('Delegado Bruno Lima (Dep. PODE/SP)', 1),
    'camaradeputados': ('Delegado Fabio Costa (Dep. PP/AL)', 1),
    'camaradosdeputados': ('Delegado Fabio Costa (Dep. PP/AL)', 1),
    'camaradeputados': ('Delegado Marcelo Freitas (Dep. UNIÃO/MG)', 1),
    'camaradosdeputados': ('Delegado Marcelo Freitas (Dep. UNIÃO/MG)', 1),
    'camaradeputados': ('Delegado Matheus Laiola (Dep. UNIÃO/PR)', 1),
    'camaradosdeputados': ('Delegado Matheus Laiola (Dep. UNIÃO/PR)', 1),
    'camaradeputados': ('Delegado Palumbo (Dep. PODE/SP)', 1),
    'camaradosdeputados': ('Delegado Palumbo (Dep. PODE/SP)', 1),
    'camaradeputados': ('Delegado da Cunha (Dep. PP/SP)', 1),
    'camaradosdeputados': ('Delegado da Cunha (Dep. PP/SP)', 1),
    'camaradeputados': ('Diego Coronel (Dep. REPUBLICANOS/BA)', 1),
    'camaradosdeputados': ('Diego Coronel (Dep. REPUBLICANOS/BA)', 1),
    'camaradeputados': ('Diego Garcia (Dep. REPUBLICANOS/PR)', 1),
    'camaradosdeputados': ('Diego Garcia (Dep. REPUBLICANOS/PR)', 1),
    'camaradeputados': ('Dilceu Sperafico (Dep. PP/PR)', 1),
    'camaradosdeputados': ('Dilceu Sperafico (Dep. PP/PR)', 1),
    'camaradeputados': ('Dimas Fabiano (Dep. PP/MG)', 1),
    'camaradosdeputados': ('Dimas Fabiano (Dep. PP/MG)', 1),
    'camaradeputados': ('Doutor Luizinho (Dep. PP/RJ)', 1),
    'camaradosdeputados': ('Doutor Luizinho (Dep. PP/RJ)', 1),
    'camaradeputados': ('Dr. Luiz Ovando (Dep. PP/MS)', 1),
    'camaradosdeputados': ('Dr. Luiz Ovando (Dep. PP/MS)', 1),
    'camaradeputados': ('Dr. Victor Linhalis (Dep. PODE/ES)', 1),
    'camaradosdeputados': ('Dr. Victor Linhalis (Dep. PODE/ES)', 1),
    'camaradeputados': ('Dr. Zacharias Calil (Dep. UNIÃO/GO)', 1),
    'camaradosdeputados': ('Dr. Zacharias Calil (Dep. UNIÃO/GO)', 1),
    'camaradeputados': ('Dra. Alessandra Haber (Dep. PODE/PA)', 1),
    'camaradosdeputados': ('Dra. Alessandra Haber (Dep. PODE/PA)', 1),
    'camaradeputados': ('Eduardo da Fonte (Dep. PP/PE)', 1),
    'camaradosdeputados': ('Eduardo da Fonte (Dep. PP/PE)', 1),
    'camaradeputados': ('Eli Borges (Dep. REPUBLICANOS/TO)', 1),
    'camaradosdeputados': ('Eli Borges (Dep. REPUBLICANOS/TO)', 1),
    'camaradeputados': ('Elmar Nascimento (Dep. UNIÃO/BA)', 1),
    'camaradosdeputados': ('Elmar Nascimento (Dep. UNIÃO/BA)', 1),
    'camaradeputados': ('Evair Vieira de Melo (Dep. PP/ES)', 1),
    'camaradosdeputados': ('Evair Vieira de Melo (Dep. PP/ES)', 1),
    'camaradeputados': ('Fabio Garcia (Dep. UNIÃO/MT)', 1),
    'camaradosdeputados': ('Fabio Garcia (Dep. UNIÃO/MT)', 1),
    'camaradeputados': ('Fabio Schiochet (Dep. UNIÃO/SC)', 1),
    'camaradosdeputados': ('Fabio Schiochet (Dep. UNIÃO/SC)', 1),
    'camaradeputados': ('Fausto Jr. (Dep. UNIÃO/AM)', 1),
    'camaradosdeputados': ('Fausto Jr. (Dep. UNIÃO/AM)', 1),
    'camaradeputados': ('Fausto Pinato (Dep. PP/SP)', 1),
    'camaradosdeputados': ('Fausto Pinato (Dep. PP/SP)', 1),
    'camaradeputados': ('Felipe Becari (Dep. PODE/SP)', 1),
    'camaradosdeputados': ('Felipe Becari (Dep. PODE/SP)', 1),
    'camaradeputados': ('Felipe Francischini (Dep. PODE/PR)', 1),
    'camaradosdeputados': ('Felipe Francischini (Dep. PODE/PR)', 1),
    'camaradeputados': ('Fernando Coelho Filho (Dep. UNIÃO/PE)', 1),
    'camaradosdeputados': ('Fernando Coelho Filho (Dep. UNIÃO/PE)', 1),
    'camaradeputados': ('Franciane Bayer (Dep. REPUBLICANOS/RS)', 1),
    'camaradosdeputados': ('Franciane Bayer (Dep. REPUBLICANOS/RS)', 1),
    'camaradeputados': ('Fred Linhares (Dep. REPUBLICANOS/DF)', 1),
    'camaradosdeputados': ('Fred Linhares (Dep. REPUBLICANOS/DF)', 1),
    'camaradeputados': ('Fábio Macedo (Dep. PODE/MA)', 1),
    'camaradosdeputados': ('Fábio Macedo (Dep. PODE/MA)', 1),
    'camaradeputados': ('Gabriel Mota (Dep. UNIÃO/RR)', 1),
    'camaradosdeputados': ('Gabriel Mota (Dep. UNIÃO/RR)', 1),
    'camaradeputados': ('Geraldo Mendes (Dep. UNIÃO/PR)', 1),
    'camaradosdeputados': ('Geraldo Mendes (Dep. UNIÃO/PR)', 1),
    'camaradeputados': ('Gilberto Abramo (Dep. REPUBLICANOS/MG)', 1),
    'camaradosdeputados': ('Gilberto Abramo (Dep. REPUBLICANOS/MG)', 1),
    'camaradeputados': ('Gilson Daniel (Dep. PODE/ES)', 1),
    'camaradosdeputados': ('Gilson Daniel (Dep. PODE/ES)', 1),
    'camaradeputados': ('Gilson Marques (Dep. NOVO/SC)', 1),
    'camaradosdeputados': ('Gilson Marques (Dep. NOVO/SC)', 1),
    'camaradeputados': ('Glaustin da Fokus (Dep. PODE/GO)', 1),
    'camaradosdeputados': ('Glaustin da Fokus (Dep. PODE/GO)', 1),
    'camaradeputados': ('Guilherme Derrite (Dep. PP/SP)', 1),
    'camaradosdeputados': ('Guilherme Derrite (Dep. PP/SP)', 1),
    'camaradeputados': ('Gustinho Ribeiro (Dep. PP/SE)', 1),
    'camaradosdeputados': ('Gustinho Ribeiro (Dep. PP/SE)', 1),
    'camaradeputados': ('Henderson Pinto (Dep. UNIÃO/PA)', 1),
    'camaradosdeputados': ('Henderson Pinto (Dep. UNIÃO/PA)', 1),
    'camaradeputados': ('Hugo Motta (Dep. REPUBLICANOS/PB)', 1),
    'camaradosdeputados': ('Hugo Motta (Dep. REPUBLICANOS/PB)', 1),
    'camaradeputados': ('Icaro de Valmir (Dep. REPUBLICANOS/SE)', 1),
    'camaradosdeputados': ('Icaro de Valmir (Dep. REPUBLICANOS/SE)', 1),
    'camaradeputados': ('Ilacir Bicalho (Dep. REPUBLICANOS/MG)', 1),
    'camaradosdeputados': ('Ilacir Bicalho (Dep. REPUBLICANOS/MG)', 1),
    'camaradeputados': ('Jadyel Alencar (Dep. REPUBLICANOS/PI)', 1),
    'camaradosdeputados': ('Jadyel Alencar (Dep. REPUBLICANOS/PI)', 1),
    'camaradeputados': ('Jorge Araújo (Dep. PP/BA)', 1),
    'camaradosdeputados': ('Jorge Araújo (Dep. PP/BA)', 1),
    'camaradeputados': ('Jorge Braz (Dep. REPUBLICANOS/RJ)', 1),
    'camaradosdeputados': ('Jorge Braz (Dep. REPUBLICANOS/RJ)', 1),
    'camaradeputados': ('Jorge Goetten (Dep. REPUBLICANOS/SC)', 1),
    'camaradosdeputados': ('Jorge Goetten (Dep. REPUBLICANOS/SC)', 1),
    'camaradeputados': ('José Nelto (Dep. UNIÃO/GO)', 1),
    'camaradosdeputados': ('José Nelto (Dep. UNIÃO/GO)', 1),
    'camaradeputados': ('José Rocha (Dep. UNIÃO/BA)', 1),
    'camaradosdeputados': ('José Rocha (Dep. UNIÃO/BA)', 1),
    'camaradeputados': ('João Maia (Dep. PP/RN)', 1),
    'camaradosdeputados': ('João Maia (Dep. PP/RN)', 1),
    'camaradeputados': ('Juarez Costa (Dep. REPUBLICANOS/MT)', 1),
    'camaradosdeputados': ('Juarez Costa (Dep. REPUBLICANOS/MT)', 1),
    'camaradeputados': ('Julio Arcoverde (Dep. PP/PI)', 1),
    'camaradosdeputados': ('Julio Arcoverde (Dep. PP/PI)', 1),
    'camaradeputados': ('Julio Cesar Ribeiro (Dep. REPUBLICANOS/DF)', 1),
    'camaradosdeputados': ('Julio Cesar Ribeiro (Dep. REPUBLICANOS/DF)', 1),
    'camaradeputados': ('Julio Lopes (Dep. PP/RJ)', 1),
    'camaradosdeputados': ('Julio Lopes (Dep. PP/RJ)', 1),
    'camaradeputados': ('Leur Lomanto Júnior (Dep. UNIÃO/BA)', 1),
    'camaradosdeputados': ('Leur Lomanto Júnior (Dep. UNIÃO/BA)', 1),
    'camaradeputados': ('Luiz Carlos Busato (Dep. UNIÃO/RS)', 1),
    'camaradosdeputados': ('Luiz Carlos Busato (Dep. UNIÃO/RS)', 1),
    'camaradeputados': ('Luiz Carlos Hauly (Dep. PODE/PR)', 1),
    'camaradosdeputados': ('Luiz Carlos Hauly (Dep. PODE/PR)', 1),
    'camaradeputados': ('Luiz Fernando Faria (Dep. UNIÃO/MG)', 1),
    'camaradosdeputados': ('Luiz Fernando Faria (Dep. UNIÃO/MG)', 1),
    'camaradeputados': ('Luiz Lima (Dep. NOVO/RJ)', 1),
    'camaradosdeputados': ('Luiz Lima (Dep. NOVO/RJ)', 1),
    'camaradeputados': ('Lula da Fonte (Dep. PP/PE)', 1),
    'camaradosdeputados': ('Lula da Fonte (Dep. PP/PE)', 1),
    'camaradeputados': ('Lêda Borges (Dep. REPUBLICANOS/GO)', 1),
    'camaradosdeputados': ('Lêda Borges (Dep. REPUBLICANOS/GO)', 1),
    'camaradeputados': ('Marangoni (Dep. UNIÃO/SP)', 1),
    'camaradosdeputados': ('Marangoni (Dep. UNIÃO/SP)', 1),
    'camaradeputados': ('Marcel van Hattem (Dep. NOVO/RS)', 1),
    'camaradosdeputados': ('Marcel van Hattem (Dep. NOVO/RS)', 1),
    'camaradeputados': ('Marcelo Crivella (Dep. REPUBLICANOS/RJ)', 1),
    'camaradosdeputados': ('Marcelo Crivella (Dep. REPUBLICANOS/RJ)', 1),
    'camaradeputados': ('Marcelo Nilo (Dep. REPUBLICANOS/BA)', 1),
    'camaradosdeputados': ('Marcelo Nilo (Dep. REPUBLICANOS/BA)', 1),
    'camaradeputados': ('Marcos Pereira (Dep. REPUBLICANOS/SP)', 1),
    'camaradosdeputados': ('Marcos Pereira (Dep. REPUBLICANOS/SP)', 1),
    'camaradeputados': ('Maria Rosas (Dep. REPUBLICANOS/SP)', 1),
    'camaradosdeputados': ('Maria Rosas (Dep. REPUBLICANOS/SP)', 1),
    'camaradeputados': ('Marussa Boldrin (Dep. REPUBLICANOS/GO)', 1),
    'camaradosdeputados': ('Marussa Boldrin (Dep. REPUBLICANOS/GO)', 1),
    'camaradeputados': ('Marx Beltrão (Dep. PP/AL)', 1),
    'camaradosdeputados': ('Marx Beltrão (Dep. PP/AL)', 1),
    'camaradeputados': ('Mauricio Neves (Dep. PP/SP)', 1),
    'camaradosdeputados': ('Mauricio Neves (Dep. PP/SP)', 1),
    'camaradeputados': ('Mauro Benevides Filho (Dep. UNIÃO/CE)', 1),
    'camaradosdeputados': ('Mauro Benevides Filho (Dep. UNIÃO/CE)', 1),
    'camaradeputados': ('Maurício Carvalho (Dep. UNIÃO/RO)', 1),
    'camaradosdeputados': ('Maurício Carvalho (Dep. UNIÃO/RO)', 1),
    'camaradeputados': ('Meire Serafim (Dep. UNIÃO/AC)', 1),
    'camaradosdeputados': ('Meire Serafim (Dep. UNIÃO/AC)', 1),
    'camaradeputados': ('Messias Donato (Dep. UNIÃO/ES)', 1),
    'camaradosdeputados': ('Messias Donato (Dep. UNIÃO/ES)', 1),
    'camaradeputados': ('Milton Vieira (Dep. REPUBLICANOS/SP)', 1),
    'camaradosdeputados': ('Milton Vieira (Dep. REPUBLICANOS/SP)', 1),
    'camaradeputados': ('Moses Rodrigues (Dep. UNIÃO/CE)', 1),
    'camaradosdeputados': ('Moses Rodrigues (Dep. UNIÃO/CE)', 1),
    'camaradeputados': ('Murillo Gouvea (Dep. UNIÃO/RJ)', 1),
    'camaradosdeputados': ('Murillo Gouvea (Dep. UNIÃO/RJ)', 1),
    'camaradeputados': ('Murilo Galdino (Dep. REPUBLICANOS/PB)', 1),
    'camaradosdeputados': ('Murilo Galdino (Dep. REPUBLICANOS/PB)', 1),
    'camaradeputados': ('Márcio Marinho (Dep. REPUBLICANOS/BA)', 1),
    'camaradosdeputados': ('Márcio Marinho (Dep. REPUBLICANOS/BA)', 1),
    'camaradeputados': ('Nelson Barbudo (Dep. PODE/MT)', 1),
    'camaradosdeputados': ('Nelson Barbudo (Dep. PODE/MT)', 1),
    'camaradeputados': ('Nely Aquino (Dep. PODE/MG)', 1),
    'camaradosdeputados': ('Nely Aquino (Dep. PODE/MG)', 1),
    'camaradeputados': ('Olival Marques (Dep. PODE/PA)', 1),
    'camaradosdeputados': ('Olival Marques (Dep. PODE/PA)', 1),
    'camaradeputados': ('Padovani (Dep. PP/PR)', 1),
    'camaradosdeputados': ('Padovani (Dep. PP/PR)', 1),
    'camaradeputados': ('Pastor Diniz (Dep. UNIÃO/RR)', 1),
    'camaradosdeputados': ('Pastor Diniz (Dep. UNIÃO/RR)', 1),
    'camaradeputados': ('Paulo Azi (Dep. UNIÃO/BA)', 1),
    'camaradosdeputados': ('Paulo Azi (Dep. UNIÃO/BA)', 1),
    'camaradeputados': ('Paulo Litro (Dep. UNIÃO/PR)', 1),
    'camaradosdeputados': ('Paulo Litro (Dep. UNIÃO/PR)', 1),
    'camaradeputados': ('Pedro Aihara (Dep. PP/MG)', 1),
    'camaradosdeputados': ('Pedro Aihara (Dep. PP/MG)', 1),
    'camaradeputados': ('Pedro Lucas Fernandes (Dep. UNIÃO/MA)', 1),
    'camaradosdeputados': ('Pedro Lucas Fernandes (Dep. UNIÃO/MA)', 1),
    'camaradeputados': ('Pedro Lupion (Dep. REPUBLICANOS/PR)', 1),
    'camaradosdeputados': ('Pedro Lupion (Dep. REPUBLICANOS/PR)', 1),
    'camaradeputados': ('Pedro Westphalen (Dep. PP/RS)', 1),
    'camaradosdeputados': ('Pedro Westphalen (Dep. PP/RS)', 1),
    'camaradeputados': ('Pinheirinho (Dep. PP/MG)', 1),
    'camaradosdeputados': ('Pinheirinho (Dep. PP/MG)', 1),
    'camaradeputados': ('Rafael Fera (Dep. PODE/RO)', 1),
    'camaradosdeputados': ('Rafael Fera (Dep. PODE/RO)', 1),
    'camaradeputados': ('Rafael Simoes (Dep. UNIÃO/MG)', 1),
    'camaradosdeputados': ('Rafael Simoes (Dep. UNIÃO/MG)', 1),
    'camaradeputados': ('Renata Abreu (Dep. PODE/SP)', 1),
    'camaradosdeputados': ('Renata Abreu (Dep. PODE/SP)', 1),
    'camaradeputados': ('Ricardo Ayres (Dep. REPUBLICANOS/TO)', 1),
    'camaradosdeputados': ('Ricardo Ayres (Dep. REPUBLICANOS/TO)', 1),
    'camaradeputados': ('Ricardo Barros (Dep. PP/PR)', 1),
    'camaradosdeputados': ('Ricardo Barros (Dep. PP/PR)', 1),
    'camaradeputados': ('Ricardo Salles (Dep. NOVO/SP)', 1),
    'camaradosdeputados': ('Ricardo Salles (Dep. NOVO/SP)', 1),
    'camaradeputados': ('Roberto Duarte (Dep. REPUBLICANOS/AC)', 1),
    'camaradosdeputados': ('Roberto Duarte (Dep. REPUBLICANOS/AC)', 1),
    'camaradeputados': ('Robinson Faria (Dep. PP/RN)', 1),
    'camaradosdeputados': ('Robinson Faria (Dep. PP/RN)', 1),
    'camaradeputados': ('Rodrigo Gambale (Dep. PODE/SP)', 1),
    'camaradosdeputados': ('Rodrigo Gambale (Dep. PODE/SP)', 1),
    'camaradeputados': ('Rodrigo de Castro (Dep. UNIÃO/MG)', 1),
    'camaradosdeputados': ('Rodrigo de Castro (Dep. UNIÃO/MG)', 1),
    'camaradeputados': ('Rogéria Santos (Dep. REPUBLICANOS/BA)', 1),
    'camaradosdeputados': ('Rogéria Santos (Dep. REPUBLICANOS/BA)', 1),
    'camaradeputados': ('Romero Rodrigues (Dep. PODE/PB)', 1),
    'camaradosdeputados': ('Romero Rodrigues (Dep. PODE/PB)', 1),
    'camaradeputados': ('Rosangela Gomes (Dep. REPUBLICANOS/RJ)', 1),
    'camaradosdeputados': ('Rosangela Gomes (Dep. REPUBLICANOS/RJ)', 1),
    'camaradeputados': ('Ruy Carneiro (Dep. PODE/PB)', 1),
    'camaradosdeputados': ('Ruy Carneiro (Dep. PODE/PB)', 1),
    'camaradeputados': ('Samuel Viana (Dep. UNIÃO/MG)', 1),
    'camaradosdeputados': ('Samuel Viana (Dep. UNIÃO/MG)', 1),
    'camaradeputados': ('Sargento Portugal (Dep. PODE/RJ)', 1),
    'camaradosdeputados': ('Sargento Portugal (Dep. PODE/RJ)', 1),
    'camaradeputados': ('Silas Câmara (Dep. REPUBLICANOS/AM)', 1),
    'camaradosdeputados': ('Silas Câmara (Dep. REPUBLICANOS/AM)', 1),
    'camaradeputados': ('Silvia Cristina (Dep. PP/RO)', 1),
    'camaradosdeputados': ('Silvia Cristina (Dep. PP/RO)', 1),
    'camaradeputados': ('Silvio Costa Filho (Dep. REPUBLICANOS/PE)', 1),
    'camaradosdeputados': ('Silvio Costa Filho (Dep. REPUBLICANOS/PE)', 1),
    'camaradeputados': ('Silvye Alves (Dep. UNIÃO/GO)', 1),
    'camaradosdeputados': ('Silvye Alves (Dep. UNIÃO/GO)', 1),
    'camaradeputados': ('Simone Marquetto (Dep. PP/SP)', 1),
    'camaradosdeputados': ('Simone Marquetto (Dep. PP/SP)', 1),
    'camaradeputados': ('Socorro Neri (Dep. PP/AC)', 1),
    'camaradosdeputados': ('Socorro Neri (Dep. PP/AC)', 1),
    'camaradeputados': ('Sérgio Turra (Dep. PP/RS)', 1),
    'camaradosdeputados': ('Sérgio Turra (Dep. PP/RS)', 1),
    'camaradeputados': ('Thiago Flores (Dep. UNIÃO/RO)', 1),
    'camaradosdeputados': ('Thiago Flores (Dep. UNIÃO/RO)', 1),
    'camaradeputados': ('Thiago de Joaldo (Dep. REPUBLICANOS/SE)', 1),
    'camaradosdeputados': ('Thiago de Joaldo (Dep. REPUBLICANOS/SE)', 1),
    'camaradeputados': ('Tiago Dimas (Dep. PODE/TO)', 1),
    'camaradosdeputados': ('Tiago Dimas (Dep. PODE/TO)', 1),
    'camaradeputados': ('Tião Medeiros (Dep. PP/PR)', 1),
    'camaradosdeputados': ('Tião Medeiros (Dep. PP/PR)', 1),
    'camaradeputados': ('Toninho Wandscheer (Dep. PP/PR)', 1),
    'camaradosdeputados': ('Toninho Wandscheer (Dep. PP/PR)', 1),
    'camaradeputados': ('Vermelho (Dep. PP/PR)', 1),
    'camaradosdeputados': ('Vermelho (Dep. PP/PR)', 1),
    'camaradeputados': ('Wilson Santiago (Dep. REPUBLICANOS/PB)', 1),
    'camaradosdeputados': ('Wilson Santiago (Dep. REPUBLICANOS/PB)', 1),
    'camaradeputados': ('Yandra Moura (Dep. UNIÃO/SE)', 1),
    'camaradosdeputados': ('Yandra Moura (Dep. UNIÃO/SE)', 1),
    'camaradeputados': ('Zezinho Barbary (Dep. PP/AC)', 1),
    'camaradosdeputados': ('Zezinho Barbary (Dep. PP/AC)', 1),
    'camaradeputados': ('Zé Adriano (Dep. PP/AC)', 1),
    'camaradosdeputados': ('Zé Adriano (Dep. PP/AC)', 1),
    'camaradeputados': ('Zé Haroldo Cathedral (Dep. UNIÃO/RR)', 1),
    'camaradosdeputados': ('Zé Haroldo Cathedral (Dep. UNIÃO/RR)', 1),
    'camaradeputados': ('Zé Silva (Dep. UNIÃO/MG)', 1),
    'camaradosdeputados': ('Zé Silva (Dep. UNIÃO/MG)', 1),
    'camaradeputados': ('Átila Lira (Dep. PP/PI)', 1),
    'camaradosdeputados': ('Átila Lira (Dep. PP/PI)', 1),

    # ── DEPUTADOS DIREITA (2) ──
    'camaradeputados': ('Adilson Barroso (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Adilson Barroso (Dep. PL/SP)', 2),
    'camaradeputados': ('Alberto Fraga (Dep. PL/DF)', 2),
    'camaradosdeputados': ('Alberto Fraga (Dep. PL/DF)', 2),
    'camaradeputados': ('Altineu Côrtes (Dep. PL/RJ)', 2),
    'camaradosdeputados': ('Altineu Côrtes (Dep. PL/RJ)', 2),
    'camaradeputados': ('André Fernandes (Dep. PL/CE)', 2),
    'camaradosdeputados': ('André Fernandes (Dep. PL/CE)', 2),
    'camaradeputados': ('André Ferreira (Dep. PL/PE)', 2),
    'camaradosdeputados': ('André Ferreira (Dep. PL/PE)', 2),
    'camaradeputados': ('Antonio Carlos Rodrigues (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Antonio Carlos Rodrigues (Dep. PL/SP)', 2),
    'camaradeputados': ('Bia Kicis (Dep. PL/DF)', 2),
    'camaradosdeputados': ('Bia Kicis (Dep. PL/DF)', 2),
    'camaradeputados': ('Bibo Nunes (Dep. PL/RS)', 2),
    'camaradosdeputados': ('Bibo Nunes (Dep. PL/RS)', 2),
    'camaradeputados': ('Cabo Gilberto Silva (Dep. PL/PB)', 2),
    'camaradosdeputados': ('Cabo Gilberto Silva (Dep. PL/PB)', 2),
    'camaradeputados': ('Capitão Alberto Neto (Dep. PL/AM)', 2),
    'camaradosdeputados': ('Capitão Alberto Neto (Dep. PL/AM)', 2),
    'camaradeputados': ('Capitão Alden (Dep. PL/BA)', 2),
    'camaradosdeputados': ('Capitão Alden (Dep. PL/BA)', 2),
    'camaradeputados': ('Capitão Augusto (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Capitão Augusto (Dep. PL/SP)', 2),
    'camaradeputados': ('Carlos Jordy (Dep. PL/RJ)', 2),
    'camaradosdeputados': ('Carlos Jordy (Dep. PL/RJ)', 2),
    'camaradeputados': ('Caroline de Toni (Dep. PL/SC)', 2),
    'camaradosdeputados': ('Caroline de Toni (Dep. PL/SC)', 2),
    'camaradeputados': ('Cezinha de Madureira (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Cezinha de Madureira (Dep. PL/SP)', 2),
    'camaradeputados': ('Chris Tonietto (Dep. PL/RJ)', 2),
    'camaradosdeputados': ('Chris Tonietto (Dep. PL/RJ)', 2),
    'camaradeputados': ('Coronel Assis (Dep. PL/MT)', 2),
    'camaradosdeputados': ('Coronel Assis (Dep. PL/MT)', 2),
    'camaradeputados': ('Coronel Chrisóstomo (Dep. PL/RO)', 2),
    'camaradosdeputados': ('Coronel Chrisóstomo (Dep. PL/RO)', 2),
    'camaradeputados': ('Coronel Fernanda (Dep. PL/MT)', 2),
    'camaradosdeputados': ('Coronel Fernanda (Dep. PL/MT)', 2),
    'camaradeputados': ('Coronel Meira (Dep. PL/PE)', 2),
    'camaradosdeputados': ('Coronel Meira (Dep. PL/PE)', 2),
    'camaradeputados': ('Dani Cunha (Dep. PL/RJ)', 2),
    'camaradosdeputados': ('Dani Cunha (Dep. PL/RJ)', 2),
    'camaradeputados': ('Daniel Agrobom (Dep. PL/GO)', 2),
    'camaradosdeputados': ('Daniel Agrobom (Dep. PL/GO)', 2),
    'camaradeputados': ('Daniel Freitas (Dep. PL/SC)', 2),
    'camaradosdeputados': ('Daniel Freitas (Dep. PL/SC)', 2),
    'camaradeputados': ('Daniela Reinehr (Dep. PL/SC)', 2),
    'camaradosdeputados': ('Daniela Reinehr (Dep. PL/SC)', 2),
    'camaradeputados': ('Delegado Caveira (Dep. PL/PA)', 2),
    'camaradosdeputados': ('Delegado Caveira (Dep. PL/PA)', 2),
    'camaradeputados': ('Delegado Paulo Bilynskyj (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Delegado Paulo Bilynskyj (Dep. PL/SP)', 2),
    'camaradeputados': ('Delegado Éder Mauro (Dep. PL/PA)', 2),
    'camaradosdeputados': ('Delegado Éder Mauro (Dep. PL/PA)', 2),
    'camaradeputados': ('Domingos Sávio (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Domingos Sávio (Dep. PL/MG)', 2),
    'camaradeputados': ('Dr Flávio (Dep. PL/RJ)', 2),
    'camaradosdeputados': ('Dr Flávio (Dep. PL/RJ)', 2),
    'camaradeputados': ('Dr. Fernando Máximo (Dep. PL/RO)', 2),
    'camaradosdeputados': ('Dr. Fernando Máximo (Dep. PL/RO)', 2),
    'camaradeputados': ('Dr. Jaziel (Dep. PL/CE)', 2),
    'camaradosdeputados': ('Dr. Jaziel (Dep. PL/CE)', 2),
    'camaradeputados': ('Emidinho Madeira (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Emidinho Madeira (Dep. PL/MG)', 2),
    'camaradeputados': ('Eros Biondini (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Eros Biondini (Dep. PL/MG)', 2),
    'camaradeputados': ('Filipe Barros (Dep. PL/PR)', 2),
    'camaradosdeputados': ('Filipe Barros (Dep. PL/PR)', 2),
    'camaradeputados': ('Filipe Martins (Dep. PL/TO)', 2),
    'camaradosdeputados': ('Filipe Martins (Dep. PL/TO)', 2),
    'camaradeputados': ('General Girão (Dep. PL/RN)', 2),
    'camaradosdeputados': ('General Girão (Dep. PL/RN)', 2),
    'camaradeputados': ('General Pazuello (Dep. PL/RJ)', 2),
    'camaradosdeputados': ('General Pazuello (Dep. PL/RJ)', 2),
    'camaradeputados': ('Gilvan da Federal (Dep. PL/ES)', 2),
    'camaradosdeputados': ('Gilvan da Federal (Dep. PL/ES)', 2),
    'camaradeputados': ('Giovani Cherini (Dep. PL/RS)', 2),
    'camaradosdeputados': ('Giovani Cherini (Dep. PL/RS)', 2),
    'camaradeputados': ('Gustavo Gayer (Dep. PL/GO)', 2),
    'camaradosdeputados': ('Gustavo Gayer (Dep. PL/GO)', 2),
    'camaradeputados': ('Helio Lopes (Dep. PL/RJ)', 2),
    'camaradosdeputados': ('Helio Lopes (Dep. PL/RJ)', 2),
    'camaradeputados': ('Ismael (Dep. PL/SC)', 2),
    'camaradosdeputados': ('Ismael (Dep. PL/SC)', 2),
    'camaradeputados': ('Jefferson Campos (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Jefferson Campos (Dep. PL/SP)', 2),
    'camaradeputados': ('Joaquim Passarinho (Dep. PL/PA)', 2),
    'camaradosdeputados': ('Joaquim Passarinho (Dep. PL/PA)', 2),
    'camaradeputados': ('José Medeiros (Dep. PL/MT)', 2),
    'camaradosdeputados': ('José Medeiros (Dep. PL/MT)', 2),
    'camaradeputados': ('João Carlos Bacelar (Dep. PL/BA)', 2),
    'camaradosdeputados': ('João Carlos Bacelar (Dep. PL/BA)', 2),
    'camaradeputados': ('Julia Zanatta (Dep. PL/SC)', 2),
    'camaradosdeputados': ('Julia Zanatta (Dep. PL/SC)', 2),
    'camaradeputados': ('Junio Amaral (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Junio Amaral (Dep. PL/MG)', 2),
    'camaradeputados': ('Lafayette de Andrada (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Lafayette de Andrada (Dep. PL/MG)', 2),
    'camaradeputados': ('Lincoln Portela (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Lincoln Portela (Dep. PL/MG)', 2),
    'camaradeputados': ('Lucio Mosquini (Dep. PL/RO)', 2),
    'camaradosdeputados': ('Lucio Mosquini (Dep. PL/RO)', 2),
    'camaradeputados': ('Luiz Carlos Motta (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Luiz Carlos Motta (Dep. PL/SP)', 2),
    'camaradeputados': ('Luiz Philippe de Orleans e Bragança (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Luiz Philippe de Orleans e Bragança (Dep. PL/SP)', 2),
    'camaradeputados': ('Magda Mofatto (Dep. PL/GO)', 2),
    'camaradosdeputados': ('Magda Mofatto (Dep. PL/GO)', 2),
    'camaradeputados': ('Marcelo Moraes (Dep. PL/RS)', 2),
    'camaradosdeputados': ('Marcelo Moraes (Dep. PL/RS)', 2),
    'camaradeputados': ('Marcelo Álvaro Antônio (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Marcelo Álvaro Antônio (Dep. PL/MG)', 2),
    'camaradeputados': ('Marcio Alvino (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Marcio Alvino (Dep. PL/SP)', 2),
    'camaradeputados': ('Marcos Pollon (Dep. PL/MS)', 2),
    'camaradosdeputados': ('Marcos Pollon (Dep. PL/MS)', 2),
    'camaradeputados': ('Mario Frias (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Mario Frias (Dep. PL/SP)', 2),
    'camaradeputados': ('Matheus Noronha (Dep. PL/CE)', 2),
    'camaradosdeputados': ('Matheus Noronha (Dep. PL/CE)', 2),
    'camaradeputados': ('Mauricio Marcon (Dep. PL/RS)', 2),
    'camaradosdeputados': ('Mauricio Marcon (Dep. PL/RS)', 2),
    'camaradeputados': ('Mauricio do Vôlei (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Mauricio do Vôlei (Dep. PL/MG)', 2),
    'camaradeputados': ('Mendonça Filho (Dep. PL/PE)', 2),
    'camaradosdeputados': ('Mendonça Filho (Dep. PL/PE)', 2),
    'camaradeputados': ('Miguel Lombardi (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Miguel Lombardi (Dep. PL/SP)', 2),
    'camaradeputados': ('Missionário José Olimpio (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Missionário José Olimpio (Dep. PL/SP)', 2),
    'camaradeputados': ('Nicoletti (Dep. PL/RR)', 2),
    'camaradosdeputados': ('Nicoletti (Dep. PL/RR)', 2),
    'camaradeputados': ('Nikolas Ferreira (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Nikolas Ferreira (Dep. PL/MG)', 2),
    'camaradeputados': ('Osmar Terra (Dep. PL/RS)', 2),
    'camaradosdeputados': ('Osmar Terra (Dep. PL/RS)', 2),
    'camaradeputados': ('Pastor Gil (Dep. PL/MA)', 2),
    'camaradosdeputados': ('Pastor Gil (Dep. PL/MA)', 2),
    'camaradeputados': ('Paulo Freire Costa (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Paulo Freire Costa (Dep. PL/SP)', 2),
    'camaradeputados': ('Paulo Marinho Jr (Dep. PL/MA)', 2),
    'camaradosdeputados': ('Paulo Marinho Jr (Dep. PL/MA)', 2),
    'camaradeputados': ('Pr. Marco Feliciano (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Pr. Marco Feliciano (Dep. PL/SP)', 2),
    'camaradeputados': ('Ricardo Guidi (Dep. PL/SC)', 2),
    'camaradosdeputados': ('Ricardo Guidi (Dep. PL/SC)', 2),
    'camaradeputados': ('Roberta Roma (Dep. PL/BA)', 2),
    'camaradosdeputados': ('Roberta Roma (Dep. PL/BA)', 2),
    'camaradeputados': ('Roberto Monteiro Pai (Dep. PL/RJ)', 2),
    'camaradosdeputados': ('Roberto Monteiro Pai (Dep. PL/RJ)', 2),
    'camaradeputados': ('Rodolfo Nogueira (Dep. PL/MS)', 2),
    'camaradosdeputados': ('Rodolfo Nogueira (Dep. PL/MS)', 2),
    'camaradeputados': ('Rodrigo Valadares (Dep. PL/SE)', 2),
    'camaradosdeputados': ('Rodrigo Valadares (Dep. PL/SE)', 2),
    'camaradeputados': ('Rodrigo da Zaeli (Dep. PL/MT)', 2),
    'camaradosdeputados': ('Rodrigo da Zaeli (Dep. PL/MT)', 2),
    'camaradeputados': ('Rosana Valle (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Rosana Valle (Dep. PL/SP)', 2),
    'camaradeputados': ('Rosangela Moro (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Rosangela Moro (Dep. PL/SP)', 2),
    'camaradeputados': ('Rosângela Reis (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Rosângela Reis (Dep. PL/MG)', 2),
    'camaradeputados': ('Sanderson (Dep. PL/RS)', 2),
    'camaradosdeputados': ('Sanderson (Dep. PL/RS)', 2),
    'camaradeputados': ('Sargento Fahur (Dep. PL/PR)', 2),
    'camaradosdeputados': ('Sargento Fahur (Dep. PL/PR)', 2),
    'camaradeputados': ('Sargento Gonçalves (Dep. PL/RN)', 2),
    'camaradosdeputados': ('Sargento Gonçalves (Dep. PL/RN)', 2),
    'camaradeputados': ('Silvio Antonio (Dep. PL/MA)', 2),
    'camaradosdeputados': ('Silvio Antonio (Dep. PL/MA)', 2),
    'camaradeputados': ('Soraya Santos (Dep. PL/RJ)', 2),
    'camaradosdeputados': ('Soraya Santos (Dep. PL/RJ)', 2),
    'camaradeputados': ('Sóstenes Cavalcante (Dep. PL/RJ)', 2),
    'camaradosdeputados': ('Sóstenes Cavalcante (Dep. PL/RJ)', 2),
    'camaradeputados': ('Vinicius Carvalho (Dep. PL/SP)', 2),
    'camaradosdeputados': ('Vinicius Carvalho (Dep. PL/SP)', 2),
    'camaradeputados': ('Vinicius Gurgel (Dep. PL/AP)', 2),
    'camaradosdeputados': ('Vinicius Gurgel (Dep. PL/AP)', 2),
    'camaradeputados': ('Zucco (Dep. PL/RS)', 2),
    'camaradosdeputados': ('Zucco (Dep. PL/RS)', 2),
    'camaradeputados': ('Zé Trovão (Dep. PL/SC)', 2),
    'camaradosdeputados': ('Zé Trovão (Dep. PL/SC)', 2),
    'camaradeputados': ('Zé Vitor (Dep. PL/MG)', 2),
    'camaradosdeputados': ('Zé Vitor (Dep. PL/MG)', 2),
}